"""Frozen contract for the Work-2 F3 minimum-manifold tangent route.

Exploratory algebra found a way to remove the first obstruction exposed by
w2_20: move *on* the w2_16 product-minimum manifold instead of approaching it
from an off-shell gradient basin.  This file freezes the resulting route
before its scientific evaluation.  It does not claim that the route is
foundation-derived and it cannot promote F3.

The declared class is deliberately narrow.  On the generic w2_16 minimum
manifold write S=s(P-I/3), R^2=(J/2)(Q-I), with rank-one projectors P,Q.  We
admit common-O(3)-equivariant isospectral motions generated by the inherited
matrix algebra, and classify their quotient-changing meridional component.
The first representative to be evaluated is Omega=[S,R^2] with

    dS/dsigma = kappa_S[Omega,S], dR/dsigma = kappa_R[Omega,R].

The curve parameter is not physical time.  A separate evaluator must decide
what the algebra proves, which choices remain imported, and whether the
existing RefG foundation selects an oriented process law.
"""

from __future__ import annotations

import hashlib
import json
from copy import deepcopy
from typing import Any


REQUIRED_SCIENTIFIC_FIELDS = frozenset({
    "CLAIM_ID", "CLAIM", "TYPE", "MODEL_VERSION", "ASSUMPTIONS", "DOMAIN",
    "CONVENTIONS", "FREEDOM_LEDGER", "DEPENDENCIES", "METHOD",
    "PASS_CONDITION", "FAIL_CONDITION", "FALSIFIER", "RESIDUAL",
    "ERROR_BOUND", "VALIDITY_HEALTH", "BRANCHES", "OBSERVABLE_MAP",
    "FORWARD_MODEL", "DATA_ROLE", "IDENTIFIABILITY", "BENCHMARK",
    "CLOSURE_FLAGS", "CROSSCHECK", "PROVENANCE", "FILES",
})

ROUTE_SPEC_KEYS = frozenset({
    "accepted_manifold", "complete_equivalence", "generator",
    "tangent_family", "quotient_coordinate", "diagnostic_representatives",
    "process_gauge", "forbidden_inputs", "evaluation_scope",
})
ORIGIN_AUDIT_SNAPSHOT_KEYS = frozenset({
    "audit_date", "audited_source_sha256", "result", "unfixed_choices",
    "public_reproducibility_boundary",
})

EVIDENCE_KEYS = frozenset({
    "dependencies_exact",
    "minimum_manifold_and_quotient_rederived",
    "generator_is_skew_and_carrier_generated",
    "flow_is_tangent_and_preserves_same_chain_F1_F2",
    "quotient_equation_exact",
    "common_motion_is_gauge_and_relative_motion_is_nongauge",
    "generic_open_stratum_is_finite_parameter_invariant",
    "gauge_invariant_quotient_intervention_response_exact",
    "raw_one_way_channel_reading_rejected_as_gauge_dependent",
    "static_law_is_flat_and_cannot_select_arrow",
    "opposite_branches_and_multiplier_freedom_are_explicit",
    "declared_foundation_sources_confirm_process_origin_open",
    "clock_metric_and_downstream_claims_quarantined",
    "independent_derivation_and_dependency_chain_pass",
})

OUTCOME_KEYS = frozenset({
    "tangent_route_evaluated",
    "same_chain_F1_F2_tangent_motion_available",
    "nongauge_quotient_direction_available",
    "conditional_oriented_order_representative_available",
    "gauge_invariant_forbidden_pair_nontransmission_available",
    "foundation_selects_sign_and_process_law",
    "foundation_derived_F3_internal_order_or_causality",
    "physical_time_or_clock",
    "foundation_to_effective_closed",
})


def frozen_route_spec() -> dict[str, Any]:
    """Independent literal freeze of the selected route and its boundaries."""
    return {
        "accepted_manifold": (
            "M_F2: S=s(P-I/3) on the positive uniaxial F1 branch, "
            "R^2=(J/2)(Q-I), J=eta/d>0, b^2!=3 alpha c, and 0<tau<1"
        ),
        "complete_equivalence": (
            "one common O(3) conjugation of the complete pair (S,R); positive "
            "reparameterisation is process gauge only after an orientation is fixed"
        ),
        "generator": (
            "Omega=[S,R^2]={R,[S,R]} is state-owned, skew, target-free and "
            "common-O(3) covariant"
        ),
        "tangent_family": (
            "dS/dsigma=kappa_S[Omega,S], dR/dsigma=kappa_R[Omega,R], with real "
            "universal coefficients used only to classify common versus relative motion"
        ),
        "quotient_coordinate": (
            "tau=1-Tr(PQ)=Tr([S,R]^T[S,R])/(s^2 J) on M_F2"
        ),
        "diagnostic_representatives": (
            "kappa_S=kappa_R is the common-gauge null; (kappa_S,kappa_R)=(1,0) "
            "and (0,-1) are two gauge lifts of the same increasing quotient branch; "
            "(0,1) has the opposite quotient sign; "
            "neither oriented branch is preselected as foundation physics"
        ),
        "process_gauge": (
            "positive changes of curve parameter preserve an already selected order; "
            "a common shift (kappa_S,kappa_R)->(kappa_S+c,kappa_R+c) is vertical "
            "path gauge; sign reversal "
            "and a zero or sign-changing state multiplier are not silently renamed gauge"
        ),
        "forbidden_inputs": (
            "physical x or t, external clock, lattice, graph, metric, GR/PN target, "
            "observed answer, preferred basis, state-external orientation, fitted "
            "mobility, or post-selected sign"
        ),
        "evaluation_scope": (
            "exact tangent algebra, quotient order, gauge-invariant quotient response, "
            "channel-lift audit and origin audit only; no persistent phase, physical "
            "time, spatial locality, metric, action, GR bridge or observation"
        ),
    }


ROUTE_SPEC = frozen_route_spec()


def route_spec_sha256(route_spec: dict[str, Any]) -> str:
    canonical = json.dumps(
        route_spec, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest().upper()


EXPECTED_ROUTE_SPEC_SHA256 = "42F0F4A6E85B52D009B206E1169A36F8C1032B6D0C51829D0D943486062E0317"


ORIGIN_AUDIT_SNAPSHOT: dict[str, Any] = {
    "audit_date": "2026-07-22",
    "audited_source_sha256": {
        "Theory_Canon.md": "BF5CABAE190821D1C0FFB342D3CDF101F13BE5386EA993BB60FCE4098F18D756",
        "intuitive/RefG_GE.md": "7E69E62C36C8CC25540E0A0465F3B74300693CA1BD868E54B4B349D5B9547981",
        "RefG/work/p01_core.py": "EA553ADE15C3C55F25B942E85DB63945CDB7EA3FBF52F938292884CEF6F4065C",
        "RefG/work/p02b_process_time_ledger.py": "55FAF1EEA2B959907044F64120695DFE5F7B36F247A6426EE8B78AC0E5E7C6EC",
        "RefG/work/p02c_dynamic_phase_clock.py": "370E0F8B83E5B88EE0081AE56ACB1AD3D800878A0BD036065C10C8B63B7BE0A0",
        "RefG/work/p03i_full_forest_to_einstein_bridge_theorem.py": "A57A3369B67DFEB617A4DD837D3E1DD9BD686EE30E3788FA6DD390E49BCED71E",
        "RefG/work/p03j_order_volume_forest_to_metric_bridge_gate.py": "06F15C8B0A7484BF915B953506809AA5420FA8592EAE528253432F68237A03CC",
        "RefG/work/p11c_population_lock_ledger.py": "87B3E0BCF2BB030979CC65B44B52534EC90D1D577ED2B1A6BD696B5BF4A7FEB1",
        "RefG/work/p11h_fmin_population_first_set_gate.py": "A1021B93ACD0263D3F4722B137C13F82C8D8137463D7FA389E6B668A6C23B443",
        "RefG/work 2/w2_18_f3_static_endpoint_adjudication_gate.py": "EF648862E22E4A87E36D55F02E7BF0EE5AB54B4C2003134774C4BDE01301D23B",
        "RefG/work 2/w2_19_f3_gradient_formation_flow_candidate_contract.py": "DF7E91E6DD4A89D2B3614B76336B5D148C9ED7204FBEF5FCA4F1D5BFA014D68A",
    },
    "result": (
        "No audited current source derives a pre-spatial transition kernel that "
        "selects the tangent quotient orientation. Effective spacetime, process-time "
        "and population-lock dynamics do not close that origin step."
    ),
    "unfixed_choices": (
        "quotient sign, process interpretation and regular invariant multiplier h(tau)"
    ),
    "public_reproducibility_boundary": (
        "ignored Canon/work sources are provenance-pinned by SHA-256 but are not runtime "
        "dependencies; tracked intuitive and Work-2 sources remain executable corroboration"
    ),
}


def origin_audit_snapshot_sha256(snapshot: dict[str, Any]) -> str:
    return route_spec_sha256(snapshot)


EXPECTED_ORIGIN_AUDIT_SNAPSHOT_SHA256 = "90911DD464DBA4C761B925D7DB6D0CAE47B9003C61CF25821310A3FA2377A34F"


def frozen_closure_flags() -> dict[str, bool]:
    return {
        "F1_F2_conditional_predecessors_registered": True,
        "w2_17_F3_contract_registered": True,
        "w2_20_predecessor_obstruction_registered": True,
        "minimum_manifold_tangent_route_contract_defined": True,
        "minimum_manifold_tangent_route_evaluated": False,
        "same_chain_F1_F2_tangent_motion_proved": False,
        "nongauge_quotient_motion_proved": False,
        "conditional_tangent_order_proved": False,
        "foundation_process_law_derived": False,
        "F3_internal_order_or_causality_proved": False,
        "physical_time_or_clock_readout_proved": False,
        "foundation_to_effective_closed": False,
        "Lorentzian_metric_or_GR_bridge_proved": False,
        "observational_validation_proved": False,
    }


EXPECTED_CLOSURE_FLAGS = frozen_closure_flags()
EXPECTED_CONTRACT_PAYLOAD_SHA256 = "A0B29EB7A57C97B5DEE69C1DEF23054E4C4723967AFF485092D8CD48D631781D"


SCIENTIFIC_CONTRACT: dict[str, Any] = {
    "CLAIM_ID": "W2_F3_MINIMUM_MANIFOLD_TANGENT_ROUTE_CONTRACT_001",
    "CLAIM": (
        "Freeze a same-chain F1/F2-preserving tangent route and test whether the "
        "inherited algebra and existing RefG foundation determine a unique oriented "
        "internal process rather than merely an unoriented quotient direction."
    ),
    "TYPE": "PREDECLARED_EXACT_ROUTE_ADJUDICATION_CONTRACT",
    "MODEL_VERSION": (
        "W2-C0 through w2_20 plus tangent-route v2 after independent gauge-lift audit. "
        "Changing the manifold, generator, "
        "equivalence, sign policy, path-lift gauge, multiplier class or process "
        "interpretation creates a new version."
    ),
    "ASSUMPTIONS": (
        "The exact conditional w2_16 F1/F2 theorem and w2_17 F3 interface are valid. "
        "The exploratory observation Omega=[S,R^2] is disclosed and is used only to "
        "select the class for prospective exact evaluation; it is not evidence that "
        "the foundation selected a process law."
    ),
    "DOMAIN": ROUTE_SPEC["accepted_manifold"],
    "CONVENTIONS": (
        "[X,Y]=XY-YX, {X,Y}=XY+YX, S^T=S, Tr(S)=0, R^T=-R, "
        "J=-Tr(R^2), and sigma is an uncalibrated curve parameter. A causal or "
        "physical-time meaning is never inferred from notation."
    ),
    "FREEDOM_LEDGER": {
        "inherited_state_and_law": {
            "source": "w2_16", "allowed_range": "A=S+R and frozen U",
            "scale": "one internal state", "complexity": 0,
        },
        "meridional_generator_class": {
            "source": "selected exploratory algebraic route",
            "allowed_range": "Omega=[S,R^2] modulo invariant scalar multiples",
            "scale": "universal route choice", "complexity": "1 discrete class",
        },
        "relative_coefficient": {
            "source": "not fixed by this contract",
            "allowed_range": (
                "kappa_S-kappa_R; evaluator must expose gauge, zero and sign branches"
            ),
            "scale": "universal process choice", "complexity": "1 real input before gauge",
        },
        "path_lift_gauge": {
            "source": "common-O(3) vertical path gauge",
            "allowed_range": (
                "only kappa_S-kappa_R survives; a common shift of both is gauge"
            ),
            "scale": "path lift, not a physical driver/responder split", "complexity": 0,
        },
        "state_multiplier": {
            "source": "not admitted in the lowest representative, audited for uniqueness",
            "allowed_range": "regular invariant h(tau)",
            "scale": "possible enlarged class", "complexity": "one free function if allowed",
        },
        "initial_state": {
            "source": "M_F2", "allowed_range": "0<tau<1 modulo common O(3)",
            "scale": "state", "complexity": "not a theory parameter",
        },
        "physical_time_metric_graph_target_or_data": {
            "source": "forbidden", "allowed_range": 0,
            "scale": "all", "complexity": 0,
        },
    },
    "DEPENDENCIES": [
        "RefG/work 2/w2_16_f2b_general_traceless_single_carrier_candidate_gate.py",
        "RefG/work 2/w2_17_f3_internal_order_causality_contract.py",
        "RefG/work 2/w2_20_f3_gradient_formation_flow_candidate_gate.py",
        "Theory_Canon.md and intuitive/RefG_GE.md origin-status audit",
    ],
    "METHOD": (
        "Re-derive the projector quotient in a canonical representative; prove exact "
        "tangency, invariants, gauge split, quotient ODE, open-domain preservation and "
        "quotient intervention response and gauge-lift equivalence; then compare opposite "
        "signs and invariant multipliers and audit every claimed foundation source."
    ),
    "PASS_CONDITION": (
        "The adjudication is valid only if every EVIDENCE_KEYS item is exactly True and "
        "the outcome map has exactly OUTCOME_KEYS. Algebraic availability and "
        "foundation derivation are reported separately; no valid report self-promotes F3."
    ),
    "FAIL_CONDITION": (
        "A failed dependency, loss of F1/F2 tangency, changed invariant, hidden target, "
        "nonboolean or missing evidence, false gauge identification, uncharged sign or "
        "multiplier, or unsupported foundation source invalidates the adjudication."
    ),
    "FALSIFIER": (
        "The underdetermination conclusion is falsified by an already existing, explicit "
        "and noncircular RefG foundation equation that uniquely fixes the tangent law "
        "and its orientation, plus a gauge-invariant factorisation if nontransmission is "
        "claimed, while preserving the frozen same-chain domain."
    ),
    "RESIDUAL": "Every symbolic identity must simplify exactly to zero.",
    "ERROR_BOUND": "Zero symbolic residual; no numerical approximation or data are used.",
    "VALIDITY_HEALTH": (
        "The compact product-minimum manifold controls finite-parameter existence. "
        "This route can establish at most conditional internal order; a 1D autonomous "
        "quotient supplies no persistent phase or physical clock."
    ),
    "BRANCHES": {
        "kappa_S_equals_kappa_R": "COMMON_O3_GAUGE_NULL",
        "kappa_S_minus_kappa_R_positive": "CONDITIONAL_TAU_INCREASING_BRANCH",
        "kappa_S_minus_kappa_R_negative": "CONDITIONAL_TAU_DECREASING_BRANCH",
        "tau_zero_or_one": "QUOTIENT_BOUNDARY_NULL",
        "state_multiplier_zero": "ADDITIONAL_FIXED_SET",
        "foundation_selected_process": "OPEN_UNEVALUATED",
        "full_F3": "FALSE_UNLESS_FOUNDATION_ORIGIN_AND_ALL_W2_17_GATES_PASS",
    },
    "OBSERVABLE_MAP": {"status": "N/A", "reason": "pre-spatial exact route audit"},
    "FORWARD_MODEL": {"status": "N/A", "reason": "no physical-time law or data"},
    "DATA_ROLE": {"status": "N/A", "reason": "no data, fit, calibration or target"},
    "IDENTIFIABILITY": (
        "The evaluator must distinguish the quotient line from its orientation, common "
        "gauge from relative motion, and positive parameter gauge from sign or h(tau)."
    ),
    "BENCHMARK": (
        "Use tau=1/2 as an interior witness; kappa_S=kappa_R as gauge null; "
        "(kappa_S,kappa_R)=(1,0) and (0,-1) as equivalent path lifts; "
        "(1,0) and (0,1) as opposite quotient signs; "
        "h=1 and h=1-2tau as non-uniqueness controls."
    ),
    "CLOSURE_FLAGS": frozen_closure_flags(),
    "CROSSCHECK": (
        "Use both full matrix commutators and the independent rank-one projector/vector "
        "derivation; run all prior Work-2 scripts and the proof-unit suite."
    ),
    "PROVENANCE": {
        "date": "2026-07-22", "data": "none",
        "route_selection": "disclosed exploratory symbolic classification",
        "code_version": "w2_21 contract version 002",
        "audit_correction": (
            "independent pre-commit audit rejected the raw one-way S/R reading as "
            "common-O(3) lift dependent"
        ),
        "contract_payload_sha256": EXPECTED_CONTRACT_PAYLOAD_SHA256,
        "route_spec_sha256": EXPECTED_ROUTE_SPEC_SHA256,
        "origin_audit_snapshot_sha256": EXPECTED_ORIGIN_AUDIT_SNAPSHOT_SHA256,
        "source_hash": "reported by the evaluator and source-control commit",
    },
    "FILES": [
        "RefG/work 2/w2_21_f3_minimum_manifold_tangent_route_contract.py",
        "RefG/work 2/w2_22_f3_minimum_manifold_tangent_route_gate.py",
    ],
}

CLAIM_CONTRACT = SCIENTIFIC_CONTRACT


def contract_payload_sha256(contract: dict[str, Any]) -> str:
    """Hash every scientific field while avoiding self-reference in provenance."""
    payload = deepcopy(contract)
    provenance = dict(payload.get("PROVENANCE", {}))
    provenance.pop("contract_payload_sha256", None)
    payload["PROVENANCE"] = provenance
    canonical = json.dumps(
        payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest().upper()


def scientific_contract_content_valid(contract: Any) -> bool:
    return bool(
        isinstance(contract, dict)
        and set(contract) == REQUIRED_SCIENTIFIC_FIELDS
        and contract_payload_sha256(contract) == EXPECTED_CONTRACT_PAYLOAD_SHA256
        and contract.get("PROVENANCE", {}).get("contract_payload_sha256")
        == EXPECTED_CONTRACT_PAYLOAD_SHA256
    )


def exact_true_map(value: Any, expected_keys: frozenset[str]) -> bool:
    return bool(
        isinstance(value, dict)
        and set(value) == expected_keys
        and all(item is True for item in value.values())
    )


def adjudication_screen(evidence: Any, outcomes: Any) -> dict[str, bool]:
    evidence_schema = bool(
        isinstance(evidence, dict)
        and set(evidence) == EVIDENCE_KEYS
        and all(type(value) is bool for value in evidence.values())
    )
    outcome_schema = bool(
        isinstance(outcomes, dict)
        and set(outcomes) == OUTCOME_KEYS
        and all(type(value) is bool for value in outcomes.values())
    )
    return {
        "valid": bool(evidence_schema and outcome_schema),
        "evidence_complete": bool(evidence_schema and all(evidence.values())),
        "promoted": False,
    }


def definition_controls() -> dict[str, bool]:
    closure = CLAIM_CONTRACT["CLOSURE_FLAGS"]
    return {
        "scientific_schema_and_content_hash_exact": scientific_contract_content_valid(
            CLAIM_CONTRACT
        ),
        "route_spec_exact_and_complete": (
            ROUTE_SPEC == frozen_route_spec()
            and set(ROUTE_SPEC) == ROUTE_SPEC_KEYS
            and route_spec_sha256(ROUTE_SPEC) == EXPECTED_ROUTE_SPEC_SHA256
            and CLAIM_CONTRACT["PROVENANCE"]["route_spec_sha256"]
            == EXPECTED_ROUTE_SPEC_SHA256
        ),
        "origin_audit_snapshot_exact_and_provenance_pinned": all((
            set(ORIGIN_AUDIT_SNAPSHOT) == ORIGIN_AUDIT_SNAPSHOT_KEYS,
            origin_audit_snapshot_sha256(ORIGIN_AUDIT_SNAPSHOT)
            == EXPECTED_ORIGIN_AUDIT_SNAPSHOT_SHA256,
            CLAIM_CONTRACT["PROVENANCE"]["origin_audit_snapshot_sha256"]
            == EXPECTED_ORIGIN_AUDIT_SNAPSHOT_SHA256,
        )),
        "freedoms_and_forbidden_inputs_explicit": all(
            key in CLAIM_CONTRACT["FREEDOM_LEDGER"]
            for key in (
                "relative_coefficient", "path_lift_gauge", "state_multiplier",
                "physical_time_metric_graph_target_or_data",
            )
        ),
        "contract_outcomes_remain_unevaluated": all((
            closure == EXPECTED_CLOSURE_FLAGS == frozen_closure_flags(),
            not closure["minimum_manifold_tangent_route_evaluated"],
            not closure["same_chain_F1_F2_tangent_motion_proved"],
            not closure["foundation_process_law_derived"],
            not closure["F3_internal_order_or_causality_proved"],
        )),
        "scope_ceiling_and_falsifier_explicit": all(
            isinstance(CLAIM_CONTRACT[key], str) and CLAIM_CONTRACT[key].strip()
            for key in ("PASS_CONDITION", "FAIL_CONDITION", "FALSIFIER", "VALIDITY_HEALTH")
        ),
    }


def fail_closed_controls() -> dict[str, bool]:
    evidence = {key: True for key in EVIDENCE_KEYS}
    outcomes = {key: False for key in OUTCOME_KEYS}
    baseline = adjudication_screen(evidence, outcomes)
    malformed: list[dict[str, bool]] = []
    for key in EVIDENCE_KEYS:
        missing = dict(evidence)
        missing.pop(key)
        malformed.append(adjudication_screen(missing, outcomes))
        nonboolean = dict(evidence)
        nonboolean[key] = 1  # type: ignore[assignment]
        malformed.append(adjudication_screen(nonboolean, outcomes))
    extra = dict(evidence)
    extra["self_attested"] = True
    malformed.append(adjudication_screen(extra, outcomes))
    missing_outcome = dict(outcomes)
    missing_outcome.pop(next(iter(missing_outcome)))
    malformed.append(adjudication_screen(evidence, missing_outcome))
    altered_contract = deepcopy(CLAIM_CONTRACT)
    altered_contract["CLAIM"] = altered_contract["CLAIM"] + " MUTATED"
    altered_route = deepcopy(ROUTE_SPEC)
    altered_route["generator"] = altered_route["generator"] + " MUTATED"
    altered_origin_audit = deepcopy(ORIGIN_AUDIT_SNAPSHOT)
    altered_origin_audit["result"] += " MUTATED"
    return {
        "complete_schema_valid_but_never_self_promotes": all((
            baseline["valid"], baseline["evidence_complete"], not baseline["promoted"]
        )),
        "malformed_maps_fail_closed": all(
            not item["valid"] and not item["promoted"] for item in malformed
        ),
        "scientific_contract_content_mutation_fails_closed": (
            not scientific_contract_content_valid(altered_contract)
        ),
        "route_spec_content_mutation_fails_closed": (
            route_spec_sha256(altered_route) != EXPECTED_ROUTE_SPEC_SHA256
        ),
        "origin_audit_snapshot_mutation_fails_closed": (
            origin_audit_snapshot_sha256(altered_origin_audit)
            != EXPECTED_ORIGIN_AUDIT_SNAPSHOT_SHA256
        ),
    }


def run() -> dict[str, Any]:
    definition = definition_controls()
    fail_closed = fail_closed_controls()
    valid = bool(all(definition.values()) and all(fail_closed.values()))
    return {
        "artifact": CLAIM_CONTRACT["CLAIM_ID"],
        "valid": valid,
        "claim": CLAIM_CONTRACT["CLAIM"],
        "route_spec": ROUTE_SPEC,
        "origin_audit_snapshot": ORIGIN_AUDIT_SNAPSHOT,
        "closure_flags": CLAIM_CONTRACT["CLOSURE_FLAGS"],
        "controls": {"definition": definition, "fail_closed": fail_closed},
        "conclusion": (
            "The same-chain tangent route, its freedom ledger and its exact evaluation "
            "boundary are frozen. No tangent result, foundation process law or F3 claim "
            "is proved by this contract."
        ),
    }


def main() -> int:
    report = run()
    print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))
    return 0 if report["valid"] is True else 1


if __name__ == "__main__":
    raise SystemExit(main())
