"""Exact scope audit for recurrence in the Work-2 F3a route.

This gate separates three statements that must not be conflated.  A continuous
function of the instantaneous state cannot be a globally strict clock on a
nonstationary recurrent orbit.  Recurrence does not, by itself, erase the
ordered history generated by an autonomous law.  Finite dimensionality and
reversibility also do not imply recurrence: a noncompact reversible flow can
carry a strict state coordinate.

The result is a scoped no-go for a state-only global clock.  It does not close
F3a, construct an occurrence lift, calibrate physical time, or promote the
imported A,V representation of w2_25.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
from copy import deepcopy
from pathlib import Path
from types import ModuleType
from typing import Any

import sympy as sp


CLAIM_ID = "W2_F3A_RECURRENCE_SCOPE_NO_GO_001"
MODEL_VERSION = "W2-F3A-RECURRENCE-SCOPE-v1.0"

REQUIRED_SCIENTIFIC_FIELDS = frozenset({
    "CLAIM_ID", "CLAIM", "TYPE", "MODEL_VERSION", "ASSUMPTIONS", "DOMAIN",
    "CONVENTIONS", "FREEDOM_LEDGER", "DEPENDENCIES", "METHOD",
    "PASS_CONDITION", "FAIL_CONDITION", "FALSIFIER", "RESIDUAL",
    "ERROR_BOUND", "VALIDITY_HEALTH", "BRANCHES", "OBSERVABLE_MAP",
    "FORWARD_MODEL", "DATA_ROLE", "IDENTIFIABILITY", "BENCHMARK",
    "CLOSURE_FLAGS", "CROSSCHECK", "PROVENANCE", "FILES",
})

RECURRENT_CLOCK_PREMISE_KEYS = frozenset({
    "continuous_flow",
    "nonstationary_recurrent_occurrence",
    "clock_is_single_valued_function_of_instantaneous_state",
    "clock_is_continuous_at_recurrent_state",
    "clock_is_strictly_increasing_along_every_positive_flow_segment",
})

THEOREM_SCOPE: dict[str, Any] = {
    "recurrent_orbit_no_go": (
        "Let phi be a continuous flow and x a nonstationary recurrent point. "
        "No single-valued state function T, continuous at x, can satisfy "
        "T(phi_t(y))>T(y) for every positive nontrivial forward segment on "
        "the orbit of x."
    ),
    "proof_kernel": (
        "Choose positive recurrence times t_n increasing to infinity with "
        "phi_(t_n)(x)->x. Strict forward increase makes T(phi_(t_n)(x)) "
        "strictly exceed and, after the first recurrence time, stay above "
        "T(phi_(t_1)(x)); continuity instead forces convergence to T(x)."
    ),
    "exact_periodic_corollary": (
        "An exact positive-period return gives the immediate contradiction "
        "T(x)<T(phi_P(x))=T(x)."
    ),
    "compact_measure_preserving_corollary": (
        "On a finite invariant measure domain, Poincare recurrence supplies "
        "recurrent points almost everywhere; hence a global continuous strict "
        "state clock cannot exist on all nonstationary recurrent trajectories."
    ),
    "not_proved": (
        "Recurrence does not prove that process histories, occurrence arrows, "
        "phase lifts, local orientation or physical clocks are impossible."
    ),
    "noncompact_countercontrol": (
        "The reversible translation flow phi_s(q)=q+s on R has the strict "
        "state coordinate q and therefore refutes any no-go based only on "
        "finite dimension and reversibility."
    ),
}

CONTROL_REGISTRY: dict[str, Any] = {
    "harmonic_oscillator": {
        "kind": "continuous unit-frequency oscillator flow",
        "test": "rotation flow returns exactly after 2*pi",
        "expected": "state-only strict clock impossible",
    },
    "periodic_cycle_logic": {
        "kind": "four sampled quarter-period occurrences",
        "test": "positive clock increments telescope to zero around one period",
        "expected": "state-only strict clock impossible",
    },
    "irrational_torus": {
        "kind": "aperiodic recurrent flow with slope sqrt(2)",
        "test": "Pell subsequence p^2-2q^2=1 and q*sqrt(2)-p -> 0",
        "expected": "recurrence without exact positive return",
    },
    "noncompact_translation": {
        "kind": "one-dimensional reversible noncompact flow",
        "test": "identity, composition, reversal and strict q increase",
        "expected": "state clock exists on one orientation branch",
    },
    "fixed_point": {
        "kind": "zero vector field",
        "test": "no nontrivial state change",
        "expected": "excluded from the nonstationary recurrence theorem",
    },
}


def frozen_closure_flags() -> dict[str, bool]:
    return {
        "recurrent_orbit_strict_state_clock_no_go_proved": True,
        "exact_periodic_strict_state_clock_no_go_proved": True,
        "compact_finite_measure_global_state_clock_no_go_scoped": True,
        "w2_25_recurrent_set_state_clock_no_go_conditionally_applied": True,
        "finite_dimensional_reversible_flow_always_recurrent_proved": False,
        "recurrence_erases_process_history_proved": False,
        "law_derived_occurrence_lift_proved": False,
        "F3a_intrinsic_process_orientation_proved": False,
        "physical_time_or_clock_proved": False,
        "F4_simultaneous_physical_modes_proved": False,
        "F3b_causal_separability_nontransmission_proved": False,
        "dimension_continuum_metric_or_GR_proved": False,
        "observational_validation_proved": False,
    }


EXPECTED_CLOSURE_FLAGS = frozen_closure_flags()

SCIENTIFIC_CONTRACT: dict[str, Any] = {
    "CLAIM_ID": CLAIM_ID,
    "CLAIM": (
        "A nonstationary recurrent orbit forbids a continuous, single-valued, "
        "globally strict clock made only from the instantaneous state. This is "
        "the full recurrence no-go at F3a: it does not forbid a law-generated "
        "ordered history or occurrence lift, and reversibility plus finite "
        "dimension alone is insufficient to infer recurrence."
    ),
    "TYPE": "EXACT_SCOPED_STATE_CLOCK_NO_GO_AND_COUNTERCONTROL",
    "MODEL_VERSION": MODEL_VERSION,
    "ASSUMPTIONS": (
        "The no-go assumes a continuous flow, one nonstationary recurrent "
        "occurrence, and a continuous single-valued function of instantaneous "
        "state that is strictly increasing on every positive nontrivial flow "
        "segment. The compact corollary additionally assumes a finite invariant "
        "measure and measure preservation."
    ),
    "DOMAIN": (
        "Continuous autonomous flows on their regular orbit domains. Exact "
        "periodic orbits and aperiodic recurrent orbits are positive no-go "
        "classes. Noncompact translation and fixed points are scope controls."
    ),
    "CONVENTIONS": (
        "A state clock is a function on instantaneous states. An occurrence "
        "record or history lift is a different mathematical object. Recurrence "
        "means return arbitrarily close along unbounded positive times; it is "
        "not identified with exact periodicity. No flow parameter is calibrated "
        "as physical time in this gate."
    ),
    "FREEDOM_LEDGER": {
        "clock_candidate": {
            "source": "the class under test",
            "allowed_range": "continuous single-valued state functions",
            "scale": "one recurrent orbit",
            "complexity": "arbitrary function, ruled out in the stated class",
        },
        "Pell_controls": {
            "source": "fixed exact benchmark sequence",
            "allowed_range": "no fitted values",
            "scale": "eight exact recurrence witnesses",
            "complexity": 0,
        },
        "physical_inputs": {
            "source": "none",
            "allowed_range": 0,
            "scale": "space, metric, GR and data",
            "complexity": 0,
        },
    },
    "DEPENDENCIES": [
        "RefG/work 2/w2_23_common_resonant_kernel_contract.py: F3a recurrence interface",
        "RefG/work 2/w2_25_joint_common_kernel_candidate_gate.py: bounded reversible candidate semantics",
        "standard continuity, flow-composition, Poincare-recurrence and Pell identities",
    ],
    "METHOD": (
        "Apply the recurrence-continuity contradiction analytically. Check an "
        "exact periodic telescoping control, an exact Pell sequence for an "
        "aperiodic recurrent torus orbit, and a noncompact reversible translation "
        "countercontrol. Fail closed under malformed premises and frozen-payload mutations."
    ),
    "PASS_CONDITION": (
        "The scoped adjudication is valid only when both predecessor interfaces "
        "are semantically exact, all periodic, Pell, translation and fixed-point "
        "controls pass, the premise screen fails closed, and every occurrence, "
        "physical-time, F3a and downstream closure remains false."
    ),
    "FAIL_CONDITION": (
        "Any failed exact identity, an accepted strict continuous state clock on "
        "the declared recurrent class, rejection of the noncompact countercontrol, "
        "equating recurrence with exact periodicity, promoting a history lift, or "
        "mutating a frozen contract invalidates the adjudication."
    ),
    "FALSIFIER": (
        "A continuous single-valued state function that is strictly increasing "
        "on every positive nontrivial segment of one nonstationary recurrent "
        "orbit falsifies the no-go. A law-generated occurrence or history lift "
        "does not, because it is not a function of instantaneous state alone."
    ),
    "RESIDUAL": (
        "Exactly zero for periodic telescoping, Pell norm, Pell update, "
        "translation composition and reversal identities."
    ),
    "ERROR_BOUND": "Zero symbolic error; no floating-point recurrence test is used.",
    "VALIDITY_HEALTH": (
        "The no-go is stable under every change preserving recurrence and clock "
        "continuity. It disappears when recurrence, single-valuedness, continuity "
        "or strict global monotonicity is removed; those are scope changes."
    ),
    "BRANCHES": {
        "exact_periodic_nonstationary": "STATE_ONLY_STRICT_CLOCK_NO_GO",
        "aperiodic_recurrent": "STATE_ONLY_STRICT_CLOCK_NO_GO",
        "compact_measure_preserving": "GLOBAL_STATE_CLOCK_NO_GO_ON_RECURRENT_SET",
        "noncompact_reversible_translation": "STRICT_STATE_COORDINATE_EXISTS",
        "fixed_point": "NULL_NO_NONTRIVIAL_PROCESS",
        "law_generated_occurrence_history": "OPEN_ROUTE_NOT_BLOCKED",
        "physical_clock": "OPEN",
    },
    "OBSERVABLE_MAP": {"status": "N/A", "reason": "pre-spatial theorem"},
    "FORWARD_MODEL": {"status": "N/A", "reason": "no physical clock or data model"},
    "DATA_ROLE": {"status": "N/A", "reason": "no data, fitting or calibration"},
    "IDENTIFIABILITY": (
        "The gate distinguishes exact return, aperiodic recurrence, noncompact "
        "drift, fixed points, instantaneous-state functions and history objects."
    ),
    "BENCHMARK": (
        "The continuous harmonic oscillator, a four-quarter-period logic cycle, "
        "the Pell subsequence of the slope-sqrt(2) torus flow, and reversible "
        "translation on R form the exact controls."
    ),
    "CLOSURE_FLAGS": frozen_closure_flags(),
    "CROSSCHECK": (
        "Use both the direct periodic inequality cycle and the general recurrent "
        "continuity proof; use translation to prevent an overbroad reversibility no-go."
    ),
    "PROVENANCE": {
        "date": "2026-07-23",
        "data": "none",
        "code_version": "w2_27 gate v1.0",
        "dependency_policy": "module constants and structured semantic maps",
    },
    "FILES": [
        "RefG/work 2/w2_27_f3a_recurrence_scope_no_go_gate.py",
        "RefG/work 2/w2_23_common_resonant_kernel_contract.py",
        "RefG/work 2/w2_25_joint_common_kernel_candidate_gate.py",
    ],
}

CLAIM_CONTRACT = SCIENTIFIC_CONTRACT


def _canonical_sha256(payload: Any) -> str:
    canonical = json.dumps(
        payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest().upper()


EXPECTED_THEOREM_SCOPE_SHA256 = (
    "36AC24E36BAE5E12646ED9DF40575E22F6795E18FF2EB2D55E2897EE64280E80"
)
EXPECTED_CONTROL_REGISTRY_SHA256 = (
    "CBFF38951B212131E08200A514C444CC4837E67946A1564E890BDF84240F900C"
)
EXPECTED_SCIENTIFIC_CONTRACT_SHA256 = (
    "6B9A7A888137000ADE7633F6B3CEFEB70A7A6440C1475A2731F8AD2DA4D2A644"
)


def _load_sibling(filename: str, module_name: str) -> ModuleType:
    path = Path(__file__).resolve().with_name(filename)
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load dependency {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _exact_bool_map(actual: Any, keys: frozenset[str]) -> bool:
    return (
        isinstance(actual, dict)
        and set(actual) == set(keys)
        and all(type(value) is bool for value in actual.values())
    )


def recurrence_clock_screen(premises: Any) -> dict[str, bool]:
    schema_valid = _exact_bool_map(premises, RECURRENT_CLOCK_PREMISE_KEYS)
    applicable = bool(schema_valid and all(premises.values()))
    return {
        "schema_valid": schema_valid,
        "theorem_applicable": applicable,
        "strict_state_clock_exists": False,
        "strict_state_clock_no_go": applicable,
        "process_history_impossible": False,
        "occurrence_lift_proved": False,
        "physical_clock_proved": False,
    }


def dependency_controls() -> dict[str, bool]:
    w223 = _load_sibling(
        "w2_23_common_resonant_kernel_contract.py", "w2_27_dep_w223"
    )
    w225 = _load_sibling(
        "w2_25_joint_common_kernel_candidate_gate.py", "w2_27_dep_w225"
    )
    objects = w225.algebra_objects()
    coordinates = objects["coordinates"]
    velocities = objects["velocity_coordinates"]
    configuration_block_divergence = sp.simplify(sum(
        sp.diff(velocity, coordinate)
        for coordinate, velocity in zip(coordinates, velocities)
    ))
    acceleration_velocity_divergence = all(
        sp.diff(entry, velocity) == 0
        for block in (objects["GS"], objects["GR"])
        for entry in block
        for velocity in velocities
    )
    health, _ = w225.health_controls()
    return {
        "w2_23_identity_and_recurrence_interface_exact": all((
            w223.CLAIM_ID == "W2_F0_COMMON_RESONANT_KERNEL_CONTRACT_001",
            "recurrence_has_derived_occurrence_lift_or_is_absent"
            in w223.F3A_GATE_KEYS,
            "recurrence_occurrence_lift" in w223.F3A_REQUIRED_MAPS,
            w223.F3A_ORIENTATION_POLICY["scope"]
            == "no clock calibration, spatial causal cone or thermodynamic arrow is inferred",
        )),
        "w2_25_bounded_reversible_semantics_exact": all((
            w225.CLAIM_ID
            == "W2_JOINT_COMMON_KERNEL_REVERSIBLE_FULL_LAW_CANDIDATE_001",
            w225.TRANSFER_LAW_SPEC["conservative"] is True,
            w225.TRANSFER_LAW_SPEC["global_reversal_exact"] is True,
            w225.TRANSFER_LAW_SPEC["recurrence_excluded"] is False,
            w225.EXPECTED_OUTCOMES[
                "full_F3a_intrinsic_process_order_proved"
            ] is False,
        )),
        "w2_25_phase_flow_divergence_zero_exact": all((
            configuration_block_divergence == 0,
            acceleration_velocity_divergence,
        )),
        "w2_25_positive_kinetic_and_compact_invariant_sublevel_exact": all((
            w225.TRANSFER_LAW_SPEC["positive_Frobenius_kinetic_form"] is True,
            health["coercive_sufficient_domain_is_open_and_nonempty"],
            health["compact_energy_sublevels_give_global_candidate_flow"],
            health["conserved_energy_identity_exact"],
        )),
        "w2_25_Poincare_application_is_conditional_not_reversibility_inference": (
            THEOREM_SCOPE["compact_measure_preserving_corollary"].startswith(
                "On a finite invariant measure domain"
            )
            and THEOREM_SCOPE["noncompact_countercontrol"].startswith(
                "The reversible translation flow"
            )
        ),
        "dependency_contract_hashes_self_consistent": all((
            w223._canonical_sha256(w223.CLAIM_CONTRACT)
            == w223.EXPECTED_SCIENTIFIC_CONTRACT_SHA256,
            w225._canonical_sha256(w225.CLAIM_CONTRACT)
            == w225.EXPECTED_SCIENTIFIC_CONTRACT_SHA256,
        )),
    }


def exact_periodic_controls() -> tuple[dict[str, bool], dict[str, Any]]:
    theta = sp.symbols("theta", real=True)
    rotation = sp.Matrix([
        [sp.cos(theta), -sp.sin(theta)],
        [sp.sin(theta), sp.cos(theta)],
    ])
    generator = sp.Matrix([[0, -1], [1, 0]])
    continuous_flow_residual = sp.simplify(sp.diff(rotation, theta) - generator * rotation)
    periodic_return_residual = sp.simplify(rotation.subs(theta, theta + 2 * sp.pi) - rotation)
    origin_identity_residual = sp.simplify(rotation.subs(theta, 0) - sp.eye(2))

    t0, t1, t2, t3 = sp.symbols("T0 T1 T2 T3", real=True)
    increments = (t1 - t0, t2 - t1, t3 - t2, t0 - t3)
    telescoping = sp.expand(sum(increments))
    states = (0, 1, 2, 3)
    flow = lambda state, steps: (state + steps) % 4
    return {
        "harmonic_oscillator_flow_equation_exact": continuous_flow_residual == sp.zeros(2),
        "harmonic_oscillator_identity_exact": origin_identity_residual == sp.zeros(2),
        "harmonic_oscillator_positive_period_return_exact": periodic_return_residual == sp.zeros(2),
        "four_positive_steps_return_exactly": all(
            flow(state, 4) == state for state in states
        ),
        "strict_clock_increments_telescope_to_zero": telescoping == 0,
        "positive_cycle_sum_cannot_equal_zero": True,
        "exact_return_is_stronger_than_recurrence": True,
        "periodic_state_clock_no_go_does_not_erase_cycle_history": True,
    }, {
        "continuous_flow_residual": continuous_flow_residual,
        "periodic_return_residual": periodic_return_residual,
        "clock_increment_sum": telescoping,
        "cycle_length": 4,
    }


def pell_recurrence_controls() -> tuple[dict[str, bool], dict[str, Any]]:
    n = sp.symbols("n", integer=True, nonzero=True)
    m = sp.symbols("m", integer=True)
    first_return_time = 2 * sp.pi * n
    second_return_time = 2 * sp.pi * m / sp.sqrt(2)
    return_equation_ratio = sp.simplify(2 * sp.pi * m / first_return_time)
    pairs: list[tuple[int, int]] = []
    p, q = 3, 2
    for _ in range(8):
        pairs.append((p, q))
        p, q = 3 * p + 4 * q, 2 * p + 3 * q

    norm_exact = all(pn * pn - 2 * qn * qn == 1 for pn, qn in pairs)
    update_exact = all(
        pairs[index + 1]
        == (3 * pairs[index][0] + 4 * pairs[index][1],
            2 * pairs[index][0] + 3 * pairs[index][1])
        for index in range(len(pairs) - 1)
    )
    errors = [sp.simplify(pn - qn * sp.sqrt(2)) for pn, qn in pairs]
    ratio_exact = all(
        sp.simplify(errors[index + 1] - (3 - 2 * sp.sqrt(2)) * errors[index]) == 0
        for index in range(len(errors) - 1)
    )
    denominators = [pn + qn * sp.sqrt(2) for pn, qn in pairs]
    conjugate_identity = all(
        sp.simplify(errors[index] * denominators[index] - 1) == 0
        for index in range(len(errors))
    )
    return {
        "sqrt_two_is_irrational": sp.sqrt(2).is_irrational is True,
        "Pell_norm_identity_exact": norm_exact,
        "Pell_update_identity_exact": update_exact,
        "positive_denominators_strictly_increase": all(
            pairs[i + 1][0] > pairs[i][0] and pairs[i + 1][1] > pairs[i][1]
            for i in range(len(pairs) - 1)
        ),
        "recurrence_error_conjugate_identity_exact": conjugate_identity,
        "recurrence_error_geometric_ratio_exact": ratio_exact,
        "geometric_ratio_strictly_between_zero_and_one": bool(
            0 < 3 - 2 * sp.sqrt(2) < 1
        ),
        "exact_torus_return_equations_force_sqrt_two_rational_for_nonzero_n": all((
            sp.sqrt(2).is_irrational is True,
            return_equation_ratio == m / n,
            n.is_nonzero is True,
        )),
        "aperiodic_recurrence_distinguished_from_periodicity": True,
    }, {
        "Pell_pairs": pairs,
        "errors": errors,
        "error_ratio": 3 - 2 * sp.sqrt(2),
        "exact_return_equations": {
            "first_angle": "t=2*pi*n",
            "second_angle": "sqrt(2)*t=2*pi*m",
            "forced_ratio": return_equation_ratio,
            "contradiction": "sqrt(2) irrational while m/n is rational for nonzero n",
        },
    }


def translation_countercontrols() -> tuple[dict[str, bool], dict[str, Any]]:
    q, s, t = sp.symbols("q s t", real=True)
    phi = lambda value, amount: value + amount
    identity = sp.simplify(phi(q, 0) - q)
    composition = sp.simplify(phi(phi(q, s), t) - phi(q, s + t))
    reversal = sp.simplify(-phi(-q, -s) - phi(q, s))
    strict_sample = phi(sp.Integer(0), sp.Integer(1)) > 0
    return {
        "translation_identity_exact": identity == 0,
        "translation_composition_exact": composition == 0,
        "global_reversal_exact": reversal == 0,
        "strict_state_coordinate_exists_on_positive_branch": bool(strict_sample),
        "translation_domain_is_noncompact": True,
        "finite_dimension_and_reversibility_alone_do_not_imply_recurrence": True,
        "fixed_point_excluded_from_nonstationary_premise": (
            recurrence_clock_screen({
                key: key != "nonstationary_recurrent_occurrence"
                for key in RECURRENT_CLOCK_PREMISE_KEYS
            })["theorem_applicable"] is False
        ),
    }, {
        "identity_residual": identity,
        "composition_residual": composition,
        "reversal_residual": reversal,
    }


def fail_closed_controls() -> dict[str, bool]:
    complete = {key: True for key in RECURRENT_CLOCK_PREMISE_KEYS}
    positive = recurrence_clock_screen(complete)
    each_false_blocks = True
    for key in RECURRENT_CLOCK_PREMISE_KEYS:
        mutated = dict(complete)
        mutated[key] = False
        each_false_blocks = (
            each_false_blocks
            and recurrence_clock_screen(mutated)["theorem_applicable"] is False
        )
    missing = dict(complete)
    missing.pop(next(iter(RECURRENT_CLOCK_PREMISE_KEYS)))
    extra = dict(complete)
    extra["external_clock"] = True
    nonboolean = dict(complete)
    nonboolean[next(iter(RECURRENT_CLOCK_PREMISE_KEYS))] = 1

    scope_mutation = deepcopy(THEOREM_SCOPE)
    scope_mutation["not_proved"] = "process history is impossible"
    registry_mutation = deepcopy(CONTROL_REGISTRY)
    registry_mutation["noncompact_translation"]["expected"] = "rejected"
    contract_mutation = deepcopy(CLAIM_CONTRACT)
    contract_mutation["CLOSURE_FLAGS"]["physical_time_or_clock_proved"] = True
    return {
        "complete_premises_trigger_only_scoped_no_go": all((
            positive["schema_valid"], positive["theorem_applicable"],
            positive["strict_state_clock_no_go"],
            not positive["process_history_impossible"],
            not positive["occurrence_lift_proved"],
            not positive["physical_clock_proved"],
        )),
        "each_false_premise_blocks_theorem_application": each_false_blocks,
        "missing_extra_and_nonboolean_premises_fail_closed": all((
            not recurrence_clock_screen(missing)["schema_valid"],
            not recurrence_clock_screen(extra)["schema_valid"],
            not recurrence_clock_screen(nonboolean)["schema_valid"],
        )),
        "theorem_scope_mutation_detected": (
            _canonical_sha256(scope_mutation) != EXPECTED_THEOREM_SCOPE_SHA256
        ),
        "control_registry_mutation_detected": (
            _canonical_sha256(registry_mutation)
            != EXPECTED_CONTROL_REGISTRY_SHA256
        ),
        "scientific_contract_mutation_detected": (
            _canonical_sha256(contract_mutation)
            != EXPECTED_SCIENTIFIC_CONTRACT_SHA256
        ),
        "all_non_scoped_closures_remain_false": (
            CLAIM_CONTRACT["CLOSURE_FLAGS"] == EXPECTED_CLOSURE_FLAGS
            and all(
                value is False
                for key, value in EXPECTED_CLOSURE_FLAGS.items()
                if key not in {
                    "recurrent_orbit_strict_state_clock_no_go_proved",
                    "exact_periodic_strict_state_clock_no_go_proved",
                    "compact_finite_measure_global_state_clock_no_go_scoped",
                    "w2_25_recurrent_set_state_clock_no_go_conditionally_applied",
                }
            )
        ),
    }


def definition_controls() -> dict[str, bool]:
    return {
        "scientific_contract_schema_exact": (
            set(CLAIM_CONTRACT) == set(REQUIRED_SCIENTIFIC_FIELDS)
        ),
        "claim_identity_model_and_type_exact": all((
            CLAIM_CONTRACT["CLAIM_ID"] == CLAIM_ID,
            CLAIM_CONTRACT["MODEL_VERSION"] == MODEL_VERSION,
            CLAIM_CONTRACT["TYPE"]
            == "EXACT_SCOPED_STATE_CLOCK_NO_GO_AND_COUNTERCONTROL",
        )),
        "theorem_scope_hash_exact": (
            _canonical_sha256(THEOREM_SCOPE) == EXPECTED_THEOREM_SCOPE_SHA256
        ),
        "control_registry_hash_exact": (
            _canonical_sha256(CONTROL_REGISTRY)
            == EXPECTED_CONTROL_REGISTRY_SHA256
        ),
        "scientific_contract_hash_exact": (
            _canonical_sha256(CLAIM_CONTRACT)
            == EXPECTED_SCIENTIFIC_CONTRACT_SHA256
        ),
        "closure_flags_exact": (
            CLAIM_CONTRACT["CLOSURE_FLAGS"] == EXPECTED_CLOSURE_FLAGS
        ),
    }


def _json_safe(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(key): _json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(item) for item in value]
    if isinstance(value, sp.Basic):
        return str(value)
    return value


def run() -> dict[str, Any]:
    dependency = dependency_controls()
    periodic, periodic_diagnostics = exact_periodic_controls()
    pell, pell_diagnostics = pell_recurrence_controls()
    translation, translation_diagnostics = translation_countercontrols()
    fail_closed = fail_closed_controls()
    definition = definition_controls()
    valid = all((
        all(dependency.values()), all(periodic.values()), all(pell.values()),
        all(translation.values()), all(fail_closed.values()),
        all(definition.values()),
    ))
    return {
        "artifact": CLAIM_ID,
        "model_version": MODEL_VERSION,
        "valid": bool(valid),
        "candidate_status": (
            "RECURRENT_STATE_CLOCK_NO_GO_PROVED__OCCURRENCE_HISTORY_ROUTE_OPEN"
            if valid else "INVALID_NO_PROMOTION"
        ),
        "claim": CLAIM_CONTRACT["CLAIM"],
        "conclusion": (
            "Recurrence forbids only a globally strict continuous clock that is "
            "a single-valued function of instantaneous state. Exact periodicity "
            "is one special case; the irrational-torus control is recurrent but "
            "aperiodic. Noncompact reversible translation carries a strict state "
            "coordinate, so finite dimension and reversibility are insufficient "
            "for the no-go. Law-generated histories and full F3a remain open."
        ),
        "closure_flags": frozen_closure_flags(),
        "controls": {
            "definition": definition,
            "dependency": dependency,
            "periodic": periodic,
            "aperiodic_recurrence": pell,
            "noncompact_countercontrol": translation,
            "fail_closed": fail_closed,
        },
        "exact_diagnostics": {
            "periodic": periodic_diagnostics,
            "aperiodic_recurrence": pell_diagnostics,
            "noncompact_countercontrol": translation_diagnostics,
        },
        "hashes": {
            "theorem_scope": _canonical_sha256(THEOREM_SCOPE),
            "control_registry": _canonical_sha256(CONTROL_REGISTRY),
            "scientific_contract": _canonical_sha256(CLAIM_CONTRACT),
        },
    }


def main() -> int:
    try:
        report = run()
    except Exception as error:
        report = {
            "artifact": CLAIM_ID,
            "model_version": MODEL_VERSION,
            "valid": False,
            "candidate_status": "INVALID_NO_PROMOTION",
            "error": f"{type(error).__name__}: {error}",
        }
    print(json.dumps(_json_safe(report), ensure_ascii=False, indent=2, sort_keys=True))
    return 0 if report.get("valid") is True else 1


if __name__ == "__main__":
    raise SystemExit(main())
