"""Exact silent-Minkowski *unreduced action* perturbative audit.

The audit starts from the covariant invariants of the displayed minimal action

    F(exp(-2 H) Y, exp(2 H) B^{AB})

and performs a formal Stückelberg expansion about

    g_{mu nu}=eta_{mu nu}, Phi=t, phi^A=x^A, H=0.

The most general SO(3)-invariant quadratic silent-point jet is kept.  The
seven-term F_min representative is audited through its exact identity as a
separate specialization.  The calculation proves a deliberately narrow
result: in the minimal F sector the material-label velocity Hessian vanishes
at quadratic order, although velocity-dependent interactions are generically
allowed at cubic order and are explicitly nonzero for F_min when its overall
coefficient is nonzero.

Despite the historical filename, this is not a reduced-spectrum gate.  Lapse, shift, scalar metric
constraints, Stückelberg fields and the H/clock mixing have not been jointly
reduced.  The tensor principal kinetic term comes from Einstein--Hilbert,
whereas the silent-point F Hessian supplies only an algebraic shear response.
The allowed but omitted C^A C^A and D_H^2 operators are included as negative
controls: either changes the corresponding quadratic velocity conclusion.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
from copy import deepcopy
from functools import lru_cache
from pathlib import Path
from types import ModuleType
from typing import Any

import sympy as sp


CLAIM_ID = "W2_SILENT_MINKOWSKI_UNREDUCED_ACTION_PERTURBATIVE_AUDIT_001"
MODEL_VERSION = "W2-SILENT-MINKOWSKI-UNREDUCED-ACTION-v1.1-DEPENDENCY-LOCKED"

W232_FILENAME = "w2_32_effective_action_dynamics_contract.py"
W232_EXPECTED_CLAIM_ID = "W2_EFFECTIVE_ACTION_DYNAMICS_CONTRACT_001"
W232_EXPECTED_MODEL_VERSION = (
    "W2-EFFECTIVE-ACTION-DYNAMICS-CONTRACT-v1.1-SYMBOLIC-CONTROLS"
)
W232_EXPECTED_ACTION_SHA256 = (
    "02E757C7406101C2E91723ED28FBE7BDD3E4F547A3968F1BD11641F97CDFF7E2"
)

REQUIRED_SCIENTIFIC_FIELDS = frozenset({
    "CLAIM_ID", "CLAIM", "TYPE", "MODEL_VERSION", "ASSUMPTIONS", "DOMAIN",
    "CONVENTIONS", "FREEDOM_LEDGER", "DEPENDENCIES", "METHOD",
    "PASS_CONDITION", "FAIL_CONDITION", "FALSIFIER", "RESIDUAL",
    "ERROR_BOUND", "VALIDITY_HEALTH", "BRANCHES", "OBSERVABLE_MAP",
    "FORWARD_MODEL", "DATA_ROLE", "IDENTIFIABILITY", "BENCHMARK",
    "CLOSURE_FLAGS", "CROSSCHECK", "PROVENANCE", "FILES",
})

JET_SPEC: dict[str, Any] = {
    "background": "g=eta, Phi=t, phi^A=x^A, H=0",
    "silent_conditions": (
        "F|_1=0", "F_,Yhat|_1=0", "F_,Bhat^{AB}|_1=0",
    ),
    "perturbations": "Phi=t+pi; phi^A=x^A+xi^A; H=h",
    "quadratic_jet": (
        "F2=(a/2)y^2+b*y*e+(kappa/2)e^2+(mu/2)Tr(E_T^2)",
    ),
    "definitions": {
        "y": "Yhat-1",
        "E": "Bhat-I_3",
        "e": "Tr(E)",
        "E_T": "E-(Tr(E)/3)I_3",
    },
    "coefficient_domain": "a,b,kappa,mu are arbitrary real silent-point Hessian coefficients",
    "regularity_split": {
        "C2_track": (
            "the epsilon^2 unreduced action coefficient and its direct material-velocity "
            "Hessian; no cubic Taylor coefficient is asserted"
        ),
        "C3_track": (
            "the epsilon^3 unreduced action coefficient, including the complete isotropic "
            "cubic Taylor jet; analytic response is a sufficient stronger assumption"
        ),
        "F_min_track": "exact polynomial identity, hence analytic",
    },
    "quadratic_scope": (
        "complete SO(3)-invariant quadratic jet for one scalar y and one "
        "symmetric 3x3 strain E"
    ),
    "cubic_scope": (
        "complete SO(3)-invariant cubic jet generated by y^3, y^2 e, y e^2, e^3, "
        "y Tr(E_T^2), e Tr(E_T^2), and Tr(E_T^3)"
    ),
    "physical_scope": "unreduced perturbative action coefficients only; no reduced spectrum",
}

FMIN_SPEC: dict[str, Any] = {
    "exact_identity": "F_min/c=(y+Tr(E))^2+16 det(E)",
    "quadratic_jet_map": {"a": "2c", "b": "2c", "kappa": "2c", "mu": "0"},
    "nonlinear_test_domain": (
        "c != 0; the cubic velocity-Hessian polynomial is nontrivial but vanishes "
        "on the surface y1+e1=0"
    ),
    "rank_statement": "quadratic silent-point Hessian has rank one only for c != 0",
}

DEPENDENCY_SPEC: dict[str, Any] = {
    "filename": W232_FILENAME,
    "claim_id": W232_EXPECTED_CLAIM_ID,
    "model_version": W232_EXPECTED_MODEL_VERSION,
    "action_spec_sha256": W232_EXPECTED_ACTION_SHA256,
    "required_report_valid": True,
    "role": (
        "authoritative frozen minimal-action scope; this audit must fail if the "
        "dependency identity, action payload or valid report drifts"
    ),
}


def frozen_outcomes() -> dict[str, bool]:
    return {
        "general_SO3_quadratic_silent_jet_classified": True,
        "covariant_linear_stueckelberg_invariants_derived": True,
        "fixed_minkowski_invariants_expanded_through_required_order": True,
        "minimal_F_material_velocity_hessian_zero_at_quadratic_order": True,
        "C2_quadratic_material_velocity_hessian_derived": True,
        "C3_full_cubic_material_velocity_hessian_derived": True,
        "Fmin_cubic_material_velocity_hessian_polynomial_nontrivial_for_c_nonzero": True,
        "projected_H_quadratic_block_spatial_and_nonlinear_time_interactions_present": True,
        "clock_H_fixed_metric_blocks_distinguished": True,
        "tensor_EH_kinetic_and_F_algebraic_shear_distinguished": True,
        "omitted_C2_and_DH2_operators_change_quadratic_velocity_blocks": True,
        "full_metric_constraint_reduction_performed": False,
        "reduced_physical_spectrum_or_DOF_health_proved": False,
        "manuscript_exterior_or_observation_retested": False,
    }


def frozen_closure_flags() -> dict[str, bool]:
    return {
        "F0_common_resonant_kernel_derived": False,
        "F1_self_differentiation_proved": False,
        "F2_operational_relations_proved": False,
        "F3a_process_orientation_proved": False,
        "F4_simultaneous_physical_modes_proved": False,
        "F3b_causal_separation_proved": False,
        "M1_dimension_continuum_proved": False,
        "M2_Lorentzian_metric_origin_proved": False,
        "A0_effective_action_origin_proved": False,
        "A1_full_action_variation_proved": False,
        "A2_conservation_no_double_count_proved": False,
        "A3_full_reduced_DOF_health_proved": False,
        "A4_universal_matter_metric_proved": False,
        "E1_reduced_action_matching_proved": False,
        "E2_exact_Einstein_entrance_proved": False,
        "source_PN_PPN_handoff_proved": False,
        "observational_validation_proved": False,
    }


EXPECTED_OUTCOMES = frozen_outcomes()
EXPECTED_CLOSURE_FLAGS = frozen_closure_flags()

CLAIM_CONTRACT: dict[str, Any] = {
    "CLAIM_ID": CLAIM_ID,
    "CLAIM": (
        "For the dependency-locked minimal F(Yhat,Bhat) sector at the silent "
        "Minkowski vacuum, derive the C2 unreduced quadratic action coefficient "
        "and its zero direct material-label velocity Hessian.  Separately, on the "
        "C3 (or analytic) track, derive the complete cubic coefficient and its "
        "material-velocity Hessian.  For nonzero F_min the latter is a nontrivial "
        "polynomial, not a pointwise nonzero coefficient.  This is an unreduced "
        "perturbative action audit, never a reduced physical spectrum."
    ),
    "TYPE": "EXACT_UNREDUCED_ACTION_PERTURBATIVE_IDENTITY_AUDIT",
    "MODEL_VERSION": MODEL_VERSION,
    "ASSUMPTIONS": (
        "Metric signature (+---); three material labels; the dependency-locked "
        "minimal invariant set F(Yhat,Bhat) and projected H-gradient operator. "
        "C2 regularity is used only for the quadratic Taylor result. C3 regularity "
        "is required for the generic cubic Taylor result; analyticity is sufficient "
        "but not silently assumed on the C2 track. No unreduced result is promoted "
        "to a physical degree of freedom or reduced spectrum."
    ),
    "DOMAIN": (
        "A formal neighborhood of g=eta, Phi=t, phi^A=x^A, H=0. The C2 "
        "quadratic identities hold for arbitrary real a,b,kappa,mu. The generic "
        "cubic coefficient belongs only to the C3/analytic track. F_min is an exact "
        "polynomial; its rank-one and nontrivial cubic controls require c != 0."
    ),
    "CONVENTIONS": {
        "signature": "+---",
        "stueckelberg_fields": "Phi=t+pi; phi^A=x^A+xi^A; H=h",
        "bookkeeping": "every perturbation and its derivative carries epsilon",
        "material_gradient": "X_Ai=partial_i xi^A",
        "velocity": "v_A=partial_0 xi^A",
        "medium_lagrangian_sign": "L_F=-M_*^4 F",
        "tensor_note": "T_ij denotes a traceless spatial metric perturbation; TT adds transversality",
        "scope_note": "all coefficients are unreduced action coefficients",
    },
    "FREEDOM_LEDGER": {
        "quadratic_Hessian_coefficients": {
            "source": "general SO(3)-invariant silent-point jet",
            "range": "a,b,kappa,mu in R",
            "complexity": "four independent quadratic coefficients",
        },
        "higher_response_jet": {
            "source": "independent C3 Taylor data, absent from the C2-only track",
            "range": "seven SO(3)-invariant cubic coefficients; higher derivatives open",
            "complexity": "used only to prove that the complete cubic jet adds no v-Hessian",
        },
        "Fmin_scale": {
            "source": "representative response normalization",
            "range": "c != 0 for rank-one and nontrivial cubic controls",
            "complexity": "one coefficient",
        },
        "background_or_data_fit": {
            "source": "none",
            "range": "N/A",
            "complexity": "no fit and no observational target",
        },
    },
    "DEPENDENCIES": {
        "authoritative_action_contract": (
            "w2_32_effective_action_dynamics_contract.py; CLAIM_ID, model version, "
            "action hash and valid report are enforced by executable controls"
        ),
        "minimal_covariant_action": (
            "artikle/RefG_Manuscript.tex, Eq. (action), used as the declared "
            "effective action rather than as a derived foundation result"
        ),
        "silent_point": "F=F_Yhat=F_Bhat=0 at Yhat=1, Bhat=I_3",
        "Fmin_identity": "the exact polynomial identity stated in the manuscript appendix",
        "upstream_physical_promotion": "none",
    },
    "METHOD": (
        "Load and validate w2_32, introduce one formal epsilon, and expand the "
        "covariant invariants. Classify the C2 quadratic jet and derive its epsilon^2 "
        "coefficient. On a separate C3 track add the complete seven-parameter "
        "isotropic cubic jet, derive the full epsilon^3 coefficient, and show that "
        "the cubic Taylor jet itself contains no material velocity. Differentiate "
        "only these unreduced action coefficients."
    ),
    "PASS_CONDITION": (
        "The w2_32 dependency identity/action hash/valid report, every C2 and C3 "
        "symbolic identity, F_min specialization, projected-H expansion, sector "
        "separation and negative/mutation control pass, while every reduced-spectrum "
        "and physical closure flag remains false."
    ),
    "FAIL_CONDITION": (
        "Dependency drift, mixing the C2 and C3 scopes, any coefficient mismatch, a "
        "nonzero minimal-F quadratic material velocity Hessian, failure of the "
        "polynomial F_min control, missed operator mutation, or promotion to a "
        "reduced physical spectrum."
    ),
    "FALSIFIER": (
        "Within the C2 minimal action, an exact epsilon^2 term depending on "
        "partial_0 xi^A falsifies the quadratic identity. Within the C3 track, a "
        "material-velocity contribution from the pure cubic Taylor jet falsifies "
        "the cubic classification. A later reduction may change interpretation, "
        "not these unreduced fixed-action coefficients."
    ),
    "RESIDUAL": "Zero for every asserted symbolic coefficient and Hessian identity.",
    "ERROR_BOUND": (
        "The epsilon^2 coefficient is exact on the C2 Taylor track. The epsilon^3 "
        "coefficient is exact only on the C3/analytic track. The projected H audit "
        "is exact through epsilon^4. No convergence radius, reduced mode or nonlinear "
        "solution estimate is claimed."
    ),
    "VALIDITY_HEALTH": {
        "quadratic_material_block": "degenerate in the minimal F sector",
        "clock_H": "fixed-metric diagonal/principal information only",
        "tensor": "EH kinetic plus algebraic F shear response, before full coupled audit",
        "full_constraint_DOF_health": "OPEN_NOT_PART_OF_THIS_UNREDUCED_ACTION_AUDIT",
        "strong_coupling": "must be assessed after complete constraint reduction and higher operators",
    },
    "BRANCHES": {
        "C2_general_quadratic_silent_jet": "UNREDUCED_ACTION_COEFFICIENT_AUDITED",
        "C3_general_cubic_silent_jet": "UNREDUCED_ACTION_COEFFICIENT_AUDITED",
        "Fmin_rank_one_representative": "AUDITED_ONLY_FOR_C_NONZERO",
        "general_fourth_and_higher_response": "OPEN",
        "reduced_physical_spectrum": "OPEN_NOT_DERIVED_OR_CLAIMED",
    },
    "OBSERVABLE_MAP": {"status": "N/A", "reason": "no observable is computed"},
    "FORWARD_MODEL": {"status": "N/A", "reason": "formal unreduced action expansion only"},
    "DATA_ROLE": {"status": "N/A", "reason": "no data, likelihood or calibration"},
    "IDENTIFIABILITY": (
        "The four C2 Hessian and seven C3 jet coefficients are algebraically "
        "distinguishable in the unreduced action. Their physical identifiability "
        "is not assessed."
    ),
    "BENCHMARK": (
        "Exact unreduced coefficient equality. The complete C3 jet must add zero "
        "material-velocity Hessian at epsilon^3. Negative controls add a silent-point "
        "linear strain term, C^A C^A, or D_H^2 and must change the relevant Hessian."
    ),
    "CLOSURE_FLAGS": frozen_closure_flags(),
    "CROSSCHECK": (
        "Direct epsilon series is compared with independent order-by-order formulas. "
        "The complete C3 Taylor jet is checked separately for velocity independence. "
        "The quadratic jet specialized to a=2c,b=2c,kappa=2c,mu=0 must reproduce "
        "the F_min cubic velocity Hessian."
    ),
    "PROVENANCE": (
        "artikle/RefG_Manuscript.tex; its exact action, silent-point conditions and "
        "F_min identity.  No manuscript file is modified by this audit."
    ),
    "FILES": (
        "RefG/work 2/w2_32_effective_action_dynamics_contract.py",
        "RefG/work 2/w2_34_silent_vacuum_reduced_spectrum_gate.py",
        "artikle/RefG_Manuscript.tex",
    ),
}


def _canonical(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _canonical(value[key]) for key in sorted(value)}
    if isinstance(value, (list, tuple)):
        return [_canonical(item) for item in value]
    if isinstance(value, (set, frozenset)):
        return sorted(_canonical(item) for item in value)
    return value


def canonical_sha256(value: Any) -> str:
    payload = json.dumps(
        _canonical(value), ensure_ascii=False, sort_keys=True, separators=(",", ":"),
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


EXPECTED_JET_SPEC_SHA256 = (
    "33bbd5a1a68168b1e82e659fecd9f95ec9c2de014071b3d76c65c05f479d2f56"
)
EXPECTED_FMIN_SPEC_SHA256 = (
    "74c898d7e5d58df3c7c58e94a88bdc0f0b24dd0b67f56d45eef3292eedb3d5d7"
)
EXPECTED_OUTCOMES_SHA256 = (
    "3d3353e3f3497a83329e3a86f3157d7ab8dc9112e1da9eee77e94babee7f909b"
)
EXPECTED_CLOSURE_SHA256 = (
    "e59b0e51ecf7e223d4df12afeae85f4b71bcdd491520174964ddc3d2f742c49b"
)
EXPECTED_DEPENDENCY_SPEC_SHA256 = (
    "a7a5f415438b183e1ad00ad3413d43a57ea3d47f14b4e87eb4096dc358038c30"
)
EXPECTED_SCIENTIFIC_CONTRACT_SHA256 = (
    "585e277ec717a852fdd71f9993fbd409f847148352d33ea59ef49473cdfc4971"
)


def _all_false(mapping: dict[str, bool]) -> bool:
    return bool(mapping) and all(value is False for value in mapping.values())


def contract_valid(contract: Any) -> bool:
    return bool(
        isinstance(contract, dict)
        and set(contract) == set(REQUIRED_SCIENTIFIC_FIELDS)
        and contract.get("CLAIM_ID") == CLAIM_ID
        and contract.get("MODEL_VERSION") == MODEL_VERSION
        and contract.get("TYPE")
        == "EXACT_UNREDUCED_ACTION_PERTURBATIVE_IDENTITY_AUDIT"
        and contract.get("CLOSURE_FLAGS") == EXPECTED_CLOSURE_FLAGS
        and _all_false(contract.get("CLOSURE_FLAGS", {}))
    )


def _load_sibling(filename: str, module_name: str) -> ModuleType:
    path = Path(__file__).resolve().with_name(filename)
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load dependency: {filename}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@lru_cache(maxsize=1)
def dependency_audit() -> tuple[dict[str, bool], dict[str, Any]]:
    w232 = _load_sibling(W232_FILENAME, "w232_for_w234")
    report = w232.run()
    report_hashes = report.get("hashes", {})
    expected_hashes = getattr(w232, "EXPECTED_HASHES", {})
    pinned_controls = report.get("pinned_hash_controls", {})
    controls = {
        "w2_32_claim_id_exact": getattr(w232, "CLAIM_ID", None)
        == W232_EXPECTED_CLAIM_ID,
        "w2_32_model_version_exact": getattr(w232, "MODEL_VERSION", None)
        == W232_EXPECTED_MODEL_VERSION,
        "w2_32_expected_action_hash_exact": (
            expected_hashes.get("action_spec") == W232_EXPECTED_ACTION_SHA256
        ),
        "w2_32_report_action_hash_exact": (
            report_hashes.get("action_spec") == W232_EXPECTED_ACTION_SHA256
        ),
        "w2_32_action_hash_control_passes": (
            pinned_controls.get("action_spec") is True
        ),
        "w2_32_valid_report_required": report.get("valid") is True,
        "w2_32_scope_status_exact": report.get("status")
        == "PASS_MINIMAL_EFFECTIVE_ACTION_SCOPE_FROZEN__ALL_DYNAMICS_HEALTH_GATES_OPEN",
        "w2_32_physical_closure_flags_remain_false": all(
            value is False for value in report.get("physical_closure_flags", {}).values()
        ),
    }
    diagnostics = {
        "artifact": report.get("artifact"),
        "model_version": report.get("model_version"),
        "valid": report.get("valid"),
        "status": report.get("status"),
        "action_spec_hash": report_hashes.get("action_spec"),
        "all_pinned_hash_controls_pass": bool(pinned_controls)
        and all(value is True for value in pinned_controls.values()),
    }
    return controls, diagnostics


def _series(expr: sp.Expr, eps: sp.Symbol, stop: int) -> sp.Expr:
    return sp.expand(sp.series(expr, eps, 0, stop).removeO())


def _matrix_series(matrix: sp.Matrix, eps: sp.Symbol, stop: int) -> sp.Matrix:
    return matrix.applyfunc(lambda item: _series(item, eps, stop))


def _coeff_matrix(matrix: sp.Matrix, eps: sp.Symbol, power: int) -> sp.Matrix:
    return matrix.applyfunc(lambda item: sp.expand(item).coeff(eps, power))


def _hessian(expr: sp.Expr, variables: tuple[sp.Symbol, ...]) -> sp.Matrix:
    return sp.Matrix([
        [sp.diff(expr, left, right) for right in variables]
        for left in variables
    ])


def _zero_matrix(matrix: sp.Matrix) -> bool:
    return all(sp.simplify(item) == 0 for item in matrix)


@lru_cache(maxsize=1)
def exact_audit() -> dict[str, Any]:
    eps = sp.symbols("epsilon", real=True)
    a, b, kappa, mu, c = sp.symbols("a b kappa mu c", real=True)
    alpha3, beta3, gamma3, delta3 = sp.symbols(
        "alpha3 beta3 gamma3 delta3", real=True
    )
    eta3, theta3, zeta3 = sp.symbols("eta3 theta3 zeta3", real=True)
    Mpl2, M4 = sp.symbols("M_Pl2 M_star4", positive=True, real=True)
    h, p0 = sp.symbols("h p0", real=True)
    p = sp.Matrix(sp.symbols("p1:4", real=True))
    v_tuple = tuple(sp.symbols("v1:4", real=True))
    v = sp.Matrix(v_tuple)
    x_symbols = sp.symbols("x11 x12 x13 x21 x22 x23 x31 x32 x33", real=True)
    X = sp.Matrix(3, 3, x_symbols)
    identity = sp.eye(3)

    # Exact fixed-Minkowski Stückelberg invariants with one bookkeeping epsilon.
    Y = (1 + eps * p0) ** 2 - eps ** 2 * (p.dot(p))
    B = (identity + eps * X) * (identity + eps * X).T - eps ** 2 * (v * v.T)
    y = _series(sp.exp(-2 * eps * h) * Y - 1, eps, 4)
    E = _matrix_series(sp.exp(2 * eps * h) * B - identity, eps, 4)
    e = sp.expand(sp.trace(E))
    ET = _matrix_series(E - e * identity / 3, eps, 4)

    y1 = sp.expand(y).coeff(eps, 1)
    y2 = sp.expand(y).coeff(eps, 2)
    E1 = _coeff_matrix(E, eps, 1)
    E2 = _coeff_matrix(E, eps, 2)
    e1 = sp.expand(e).coeff(eps, 1)
    e2 = sp.expand(e).coeff(eps, 2)
    ET1 = _coeff_matrix(ET, eps, 1)

    expected_y1 = 2 * (p0 - h)
    expected_y2 = p0 ** 2 - p.dot(p) - 4 * h * p0 + 2 * h ** 2
    expected_E1 = X + X.T + 2 * h * identity
    expected_E2 = X * X.T - v * v.T + 2 * h * (X + X.T) + 2 * h ** 2 * identity
    expected_e1 = sp.trace(expected_E1)
    expected_e2 = sp.trace(expected_E2)
    expected_ET1 = expected_E1 - expected_e1 * identity / 3

    Fjet = _series(
        a * y ** 2 / 2
        + b * y * e
        + kappa * e ** 2 / 2
        + mu * sp.trace(ET * ET) / 2,
        eps,
        4,
    )
    Fjet2 = sp.expand(Fjet).coeff(eps, 2)
    Fjet3 = sp.expand(Fjet).coeff(eps, 3)
    expected_Fjet2 = sp.expand(
        a * y1 ** 2 / 2
        + b * y1 * e1
        + kappa * e1 ** 2 / 2
        + mu * sp.trace(ET1 * ET1) / 2
    )
    expected_Fjet3 = sp.expand(
        a * y1 * y2
        + b * (y1 * e2 + y2 * e1)
        + kappa * e1 * e2
        + mu * sp.trace(ET1 * (E2 - e2 * identity / 3))
    )

    # Complete SO(3)-invariant cubic Taylor jet.  This object belongs only to
    # the C3/analytic track.  It depends exclusively on first-order invariants,
    # which contain no material velocity, so it cannot change the epsilon^3
    # material-velocity Hessian induced by the quadratic jet.
    cubic_taylor_jet3 = sp.expand(
        alpha3 * y1**3 / 6
        + beta3 * y1**2 * e1 / 2
        + gamma3 * y1 * e1**2 / 2
        + delta3 * e1**3 / 6
        + eta3 * y1 * sp.trace(ET1 * ET1) / 2
        + theta3 * e1 * sp.trace(ET1 * ET1) / 2
        + zeta3 * sp.trace(ET1 * ET1 * ET1) / 3
    )
    full_C3_coefficient = sp.expand(Fjet3 + cubic_taylor_jet3)

    velocity_hessian_quadratic = _hessian(Fjet2, v_tuple)
    velocity_hessian_cubic = _hessian(Fjet3, v_tuple)
    cubic_taylor_jet_velocity_hessian = _hessian(cubic_taylor_jet3, v_tuple)
    full_C3_velocity_hessian = _hessian(full_C3_coefficient, v_tuple)
    lagrangian_velocity_hessian_quadratic = -M4 * velocity_hessian_quadratic
    lagrangian_velocity_hessian_cubic = -M4 * velocity_hessian_cubic
    expected_velocity_hessian_cubic = -2 * (
        (b * y1 + kappa * e1) * identity + mu * ET1
    )

    # Exact F_min identity.  det(E) starts at cubic order, so it contributes
    # det(E1) at epsilon^3 but no material velocity until a later order.
    Fmin = _series(c * ((y + e) ** 2 + 16 * E.det()), eps, 4)
    Fmin2 = sp.expand(Fmin).coeff(eps, 2)
    Fmin3 = sp.expand(Fmin).coeff(eps, 3)
    expected_Fmin2 = sp.expand(c * (y1 + e1) ** 2)
    expected_Fmin3 = sp.expand(
        2 * c * (y1 + e1) * (y2 + e2) + 16 * c * E1.det()
    )
    Fmin_velocity_hessian_quadratic = _hessian(Fmin2, v_tuple)
    # Cancel removable rational artifacts introduced by SymPy's formal series
    # engine so the exact polynomial is defined also on y1+e1=0.
    Fmin_velocity_hessian_cubic = _hessian(Fmin3, v_tuple).applyfunc(sp.cancel)
    expected_Fmin_velocity_hessian_cubic = -4 * c * (y1 + e1) * identity
    general_to_Fmin_hessian = velocity_hessian_cubic.subs({
        a: 2 * c, b: 2 * c, kappa: 2 * c, mu: 0,
    })

    # First-order covariant expressions before setting metric perturbations to
    # zero.  No material velocity appears in either invariant at this order.
    n00 = sp.symbols("n00", real=True)
    q11, q22, q33, q12, q13, q23 = sp.symbols(
        "q11 q22 q33 q12 q13 q23", real=True,
    )
    Q = sp.Matrix([
        [q11, q12, q13], [q12, q22, q23], [q13, q23, q33],
    ])
    covariant_y1 = 2 * p0 - n00 - 2 * h
    covariant_E1 = X + X.T + Q + 2 * h * identity
    covariant_velocity_derivatives = tuple(
        sp.diff(covariant_y1, item) for item in v_tuple
    ) + tuple(
        sp.diff(component, item)
        for component in covariant_E1
        for item in v_tuple
    )

    # Fixed-metric clock/H scalar block of F2.  This is not the scalar metric
    # constraint reduction.
    zero_X = {symbol: 0 for symbol in x_symbols}
    fixed_clock_H_F2 = sp.expand(Fjet2.subs(zero_X))
    expected_fixed_clock_H_F2 = sp.expand(
        2 * a * (p0 - h) ** 2
        + 12 * b * h * (p0 - h)
        + 18 * kappa * h ** 2
    )
    clock_F_velocity_hessian = sp.diff(fixed_clock_H_F2, p0, p0)

    # The projected H-gradient Z_H=(X_H^2/Y)-K is expanded one order farther
    # to display both its cubic time interaction and quartic dot(h)^2 term.
    ht = sp.symbols("h_t", real=True)
    hgrad = sp.Matrix(sp.symbols("h1:4", real=True))
    XH = eps * ht * (1 + eps * p0) - eps ** 2 * p.dot(hgrad)
    K = eps ** 2 * (ht ** 2 - hgrad.dot(hgrad))
    ZH = _series(XH ** 2 / Y - K, eps, 5)
    ZH2 = sp.expand(ZH).coeff(eps, 2)
    ZH3 = sp.expand(ZH).coeff(eps, 3)
    ZH4 = sp.expand(ZH).coeff(eps, 4)
    pdoth = p.dot(hgrad)
    expected_ZH2 = hgrad.dot(hgrad)
    expected_ZH3 = -2 * ht * pdoth
    expected_ZH4 = p.dot(p) * ht ** 2 + 2 * p0 * ht * pdoth + pdoth ** 2

    # Pure traceless spatial tensor response.  On a wave along one axis, u and
    # w are the two TT polarizations.  F has no metric derivatives; EH supplies
    # the standard tensor principal kinetic term.
    u, w, udot, wdot = sp.symbols("u w u_dot w_dot", real=True)
    Ttt = sp.Matrix([[u, w, 0], [w, -u, 0], [0, 0, 0]])
    tensor_F2 = sp.expand(mu * sp.trace(Ttt * Ttt) / 2)
    expected_tensor_F2 = mu * (u ** 2 + w ** 2)
    tensor_F_velocity_hessian = _hessian(tensor_F2, (udot, wdot))
    EH_TT_kinetic = Mpl2 * (udot ** 2 + wdot ** 2) / 4
    EH_TT_velocity_hessian = _hessian(EH_TT_kinetic, (udot, wdot))

    # Negative controls for the scope of the minimal truncation.
    ell = sp.symbols("ell", real=True)
    linear_strain_mutation2 = sp.expand(ell * e).coeff(eps, 2)
    linear_strain_velocity_hessian = _hessian(linear_strain_mutation2, v_tuple)

    # C^A = dPhi.dphi^A.  Its first-order value is v_A-p_A, so C^A C^A
    # supplies a direct material velocity Hessian at quadratic order.
    Cvec = (
        eps * v * (1 + eps * p0)
        - eps * p
        - eps ** 2 * X * p
    )
    C2 = _series(Cvec.dot(Cvec), eps, 3).coeff(eps, 2)
    C2_velocity_hessian = _hessian(C2, v_tuple)

    DH2 = _series(XH ** 2 / Y, eps, 3).coeff(eps, 2)
    DH2_time_hessian = sp.diff(DH2, ht, ht)

    identities = {
        "SO3_quadratic_jet_has_exactly_four_registered_coefficients": (
            len({a, b, kappa, mu}) == 4
        ),
        "SO3_cubic_jet_has_exactly_seven_registered_coefficients": (
            len({alpha3, beta3, gamma3, delta3, eta3, theta3, zeta3}) == 7
        ),
        "fixed_invariant_y_first_order_exact": sp.simplify(y1 - expected_y1) == 0,
        "fixed_invariant_y_second_order_exact": sp.simplify(y2 - expected_y2) == 0,
        "fixed_invariant_E_first_order_exact": _zero_matrix(E1 - expected_E1),
        "fixed_invariant_E_second_order_exact": _zero_matrix(E2 - expected_E2),
        "trace_coefficients_exact": all((
            sp.simplify(e1 - expected_e1) == 0,
            sp.simplify(e2 - expected_e2) == 0,
            _zero_matrix(ET1 - expected_ET1),
        )),
        "general_jet_quadratic_coefficient_exact": sp.simplify(Fjet2 - expected_Fjet2) == 0,
        "general_jet_cubic_coefficient_exact": sp.simplify(Fjet3 - expected_Fjet3) == 0,
        "material_velocity_hessian_quadratic_zero": _zero_matrix(velocity_hessian_quadratic),
        "material_velocity_hessian_cubic_formula_exact": _zero_matrix(
            velocity_hessian_cubic - expected_velocity_hessian_cubic
        ),
        "complete_C3_cubic_taylor_jet_has_zero_material_velocity_hessian": (
            _zero_matrix(cubic_taylor_jet_velocity_hessian)
        ),
        "full_C3_cubic_material_velocity_hessian_formula_exact": _zero_matrix(
            full_C3_velocity_hessian - expected_velocity_hessian_cubic
        ),
        "Fmin_quadratic_coefficient_exact": sp.simplify(Fmin2 - expected_Fmin2) == 0,
        "Fmin_cubic_coefficient_exact": sp.simplify(Fmin3 - expected_Fmin3) == 0,
        "Fmin_quadratic_velocity_hessian_zero": _zero_matrix(
            Fmin_velocity_hessian_quadratic
        ),
        "Fmin_cubic_velocity_hessian_exact": _zero_matrix(
            Fmin_velocity_hessian_cubic - expected_Fmin_velocity_hessian_cubic
        ),
        "general_jet_specializes_to_Fmin_velocity_hessian": _zero_matrix(
            general_to_Fmin_hessian - Fmin_velocity_hessian_cubic
        ),
        "Fmin_cubic_velocity_hessian_polynomial_not_identically_zero_for_c_nonzero": (
            not _zero_matrix(Fmin_velocity_hessian_cubic.subs(c, 1))
        ),
        "Fmin_cubic_velocity_hessian_vanishes_on_linear_trace_surface": (
            _zero_matrix(Fmin_velocity_hessian_cubic.subs(
                p0, -sp.trace(X) - 2 * h
            ))
        ),
        "covariant_first_order_invariants_contain_no_material_velocity": all(
            item == 0 for item in covariant_velocity_derivatives
        ),
        "covariant_to_fixed_background_linear_match": all((
            sp.simplify(covariant_y1.subs(n00, 0) - y1) == 0,
            _zero_matrix(covariant_E1.subs({
                q11: 0, q22: 0, q33: 0, q12: 0, q13: 0, q23: 0,
            }) - E1),
        )),
        "fixed_clock_H_quadratic_block_exact": (
            sp.simplify(fixed_clock_H_F2 - expected_fixed_clock_H_F2) == 0
        ),
        "clock_fixed_metric_F_velocity_hessian_is_4a": (
            sp.simplify(clock_F_velocity_hessian - 4 * a) == 0
        ),
        "projected_H_quadratic_spatial_block_exact": sp.simplify(ZH2 - expected_ZH2) == 0,
        "projected_H_cubic_time_interaction_exact": sp.simplify(ZH3 - expected_ZH3) == 0,
        "projected_H_quartic_time_interaction_exact": sp.simplify(ZH4 - expected_ZH4) == 0,
        "projected_H_quadratic_time_hessian_zero": sp.diff(ZH2, ht, ht) == 0,
        "tensor_F_is_algebraic_shear_response": all((
            sp.simplify(tensor_F2 - expected_tensor_F2) == 0,
            _zero_matrix(tensor_F_velocity_hessian),
        )),
        "tensor_EH_principal_velocity_hessian_nonzero": (
            EH_TT_velocity_hessian == sp.diag(Mpl2 / 2, Mpl2 / 2)
        ),
    }

    negative_controls = {
        "linear_silent_point_strain_mutation_creates_quadratic_label_velocity": (
            linear_strain_velocity_hessian == -2 * ell * identity
        ),
        "omitted_C_squared_creates_quadratic_label_velocity": (
            C2_velocity_hessian == 2 * identity
        ),
        "omitted_DH_squared_creates_quadratic_H_time_velocity": (
            sp.simplify(DH2_time_hessian - 2) == 0
        ),
        "zero_Fmin_scale_removes_specific_nonlinear_control": _zero_matrix(
            Fmin_velocity_hessian_cubic.subs(c, 0)
        ),
        "wrong_cubic_hessian_coefficient_is_detected": not _zero_matrix(
            Fmin_velocity_hessian_cubic
            - (-2 * c * (y1 + e1) * identity)
        ),
    }

    compact_results = {
        "linear_invariants": {
            "y1": y1,
            "E1": E1,
            "trace_E1": e1,
        },
        "quadratic_material_velocity_hessian_F": velocity_hessian_quadratic,
        "leading_cubic_material_velocity_hessian_F": velocity_hessian_cubic,
        "complete_C3_cubic_taylor_jet": cubic_taylor_jet3,
        "cubic_taylor_jet_material_velocity_hessian": (
            cubic_taylor_jet_velocity_hessian
        ),
        "full_C3_material_velocity_hessian": full_C3_velocity_hessian,
        "leading_cubic_material_velocity_hessian_Fmin": Fmin_velocity_hessian_cubic,
        "quadratic_material_velocity_hessian_LF": lagrangian_velocity_hessian_quadratic,
        "leading_cubic_material_velocity_hessian_LF": lagrangian_velocity_hessian_cubic,
        "leading_cubic_material_velocity_hessian_LFmin": (
            -M4 * Fmin_velocity_hessian_cubic
        ),
        "fixed_clock_H_F2": fixed_clock_H_F2,
        "clock_F_hessian_before_Lagrangian_sign": clock_F_velocity_hessian,
        "clock_LF_velocity_hessian_fixed_metric": -M4 * clock_F_velocity_hessian,
        "projected_H_coefficients": {"epsilon2": ZH2, "epsilon3": ZH3, "epsilon4": ZH4},
        "tensor": {
            "F2_two_polarizations": tensor_F2,
            "F_velocity_hessian": tensor_F_velocity_hessian,
            "EH_velocity_hessian": EH_TT_velocity_hessian,
        },
        "scope_controls": {
            "linear_strain_velocity_hessian": linear_strain_velocity_hessian,
            "C2_velocity_hessian": C2_velocity_hessian,
            "DH2_time_hessian": DH2_time_hessian,
        },
    }

    return {
        "symbols": {
            "epsilon": eps, "a": a, "b": b, "kappa": kappa,
            "mu": mu, "c": c, "M4": M4,
            "C3_coefficients": (
                alpha3, beta3, gamma3, delta3, eta3, theta3, zeta3,
            ),
        },
        "identities": identities,
        "negative_controls": negative_controls,
        "compact_results": compact_results,
    }


def _serialize(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _serialize(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_serialize(item) for item in value]
    if isinstance(value, sp.MatrixBase):
        return [[str(sp.simplify(value[i, j])) for j in range(value.cols)] for i in range(value.rows)]
    if isinstance(value, sp.Basic):
        return str(sp.simplify(value))
    return value


def evaluate() -> dict[str, Any]:
    dependency, dependency_diagnostics = dependency_audit()
    audit = exact_audit()
    hashes = {
        "jet_spec": canonical_sha256(JET_SPEC),
        "Fmin_spec": canonical_sha256(FMIN_SPEC),
        "dependency_spec": canonical_sha256(DEPENDENCY_SPEC),
        "outcomes": canonical_sha256(EXPECTED_OUTCOMES),
        "closure_flags": canonical_sha256(EXPECTED_CLOSURE_FLAGS),
        "scientific_contract": canonical_sha256(CLAIM_CONTRACT),
    }
    expected_hashes = {
        "jet_spec": EXPECTED_JET_SPEC_SHA256,
        "Fmin_spec": EXPECTED_FMIN_SPEC_SHA256,
        "dependency_spec": EXPECTED_DEPENDENCY_SPEC_SHA256,
        "outcomes": EXPECTED_OUTCOMES_SHA256,
        "closure_flags": EXPECTED_CLOSURE_SHA256,
        "scientific_contract": EXPECTED_SCIENTIFIC_CONTRACT_SHA256,
    }
    hash_controls = {
        "all_scientific_hashes_pinned": hashes == expected_hashes,
        "jet_spec_mutation_detected": (
            canonical_sha256({**JET_SPEC, "physical_scope": "mutated"})
            != hashes["jet_spec"]
        ),
        "Fmin_spec_mutation_detected": (
            canonical_sha256({**FMIN_SPEC, "nonlinear_test_domain": "all c"})
            != hashes["Fmin_spec"]
        ),
        "outcome_promotion_mutation_detected": (
            canonical_sha256({
                **EXPECTED_OUTCOMES,
                "full_metric_constraint_reduction_performed": True,
            }) != hashes["outcomes"]
        ),
        "closure_promotion_mutation_detected": (
            canonical_sha256({
                **EXPECTED_CLOSURE_FLAGS,
                "A3_full_reduced_DOF_health_proved": True,
            }) != hashes["closure_flags"]
        ),
        "dependency_spec_mutation_detected": (
            canonical_sha256({**DEPENDENCY_SPEC, "action_spec_sha256": "MUTATED"})
            != hashes["dependency_spec"]
        ),
        "contract_scope_mutation_detected": (
            canonical_sha256({**CLAIM_CONTRACT, "TYPE": "REDUCED_SPECTRUM"})
            != hashes["scientific_contract"]
        ),
    }
    semantic_controls = {
        "contract_exact_and_fail_closed": contract_valid(CLAIM_CONTRACT),
        "expected_outcomes_exact": frozen_outcomes() == EXPECTED_OUTCOMES,
        "all_physical_closure_flags_false": _all_false(EXPECTED_CLOSURE_FLAGS),
        "full_reduced_spectrum_explicitly_false": all((
            EXPECTED_OUTCOMES["full_metric_constraint_reduction_performed"] is False,
            EXPECTED_OUTCOMES["reduced_physical_spectrum_or_DOF_health_proved"] is False,
            CLAIM_CONTRACT["BRANCHES"]["reduced_physical_spectrum"]
            == "OPEN_NOT_DERIVED_OR_CLAIMED",
        )),
        "C2_and_C3_regularities_separated": all((
            "C2 regularity is used only for the quadratic"
            in CLAIM_CONTRACT["ASSUMPTIONS"],
            "C3 regularity is required" in CLAIM_CONTRACT["ASSUMPTIONS"],
            "unreduced" in CLAIM_CONTRACT["CLAIM"],
        )),
        "minimal_truncation_scope_explicit": all((
            "minimal" in CLAIM_CONTRACT["ASSUMPTIONS"],
            "C^A C^A" in CLAIM_CONTRACT["BENCHMARK"],
            "D_H^2" in CLAIM_CONTRACT["BENCHMARK"],
        )),
    }
    identities_pass = bool(audit["identities"]) and all(audit["identities"].values())
    negative_controls_pass = bool(audit["negative_controls"]) and all(
        audit["negative_controls"].values()
    )
    identity = audit["identities"]
    negative = audit["negative_controls"]
    outcome_support_controls = {
        "general_SO3_quadratic_silent_jet_classified": all((
            identity["SO3_quadratic_jet_has_exactly_four_registered_coefficients"],
            identity["general_jet_quadratic_coefficient_exact"],
        )),
        "covariant_linear_stueckelberg_invariants_derived": all((
            identity["covariant_first_order_invariants_contain_no_material_velocity"],
            identity["covariant_to_fixed_background_linear_match"],
        )),
        "fixed_minkowski_invariants_expanded_through_required_order": all((
            identity["fixed_invariant_y_first_order_exact"],
            identity["fixed_invariant_y_second_order_exact"],
            identity["fixed_invariant_E_first_order_exact"],
            identity["fixed_invariant_E_second_order_exact"],
        )),
        "minimal_F_material_velocity_hessian_zero_at_quadratic_order": identity[
            "material_velocity_hessian_quadratic_zero"
        ],
        "C2_quadratic_material_velocity_hessian_derived": all((
            identity["general_jet_quadratic_coefficient_exact"],
            identity["material_velocity_hessian_quadratic_zero"],
        )),
        "C3_full_cubic_material_velocity_hessian_derived": all((
            identity["SO3_cubic_jet_has_exactly_seven_registered_coefficients"],
            identity["general_jet_cubic_coefficient_exact"],
            identity["complete_C3_cubic_taylor_jet_has_zero_material_velocity_hessian"],
            identity["full_C3_cubic_material_velocity_hessian_formula_exact"],
        )),
        "Fmin_cubic_material_velocity_hessian_polynomial_nontrivial_for_c_nonzero": all((
            identity[
                "Fmin_cubic_velocity_hessian_polynomial_not_identically_zero_for_c_nonzero"
            ],
            identity["Fmin_cubic_velocity_hessian_vanishes_on_linear_trace_surface"],
        )),
        "projected_H_quadratic_block_spatial_and_nonlinear_time_interactions_present": all((
            identity["projected_H_quadratic_spatial_block_exact"],
            identity["projected_H_cubic_time_interaction_exact"],
            identity["projected_H_quartic_time_interaction_exact"],
            identity["projected_H_quadratic_time_hessian_zero"],
        )),
        "clock_H_fixed_metric_blocks_distinguished": all((
            identity["fixed_clock_H_quadratic_block_exact"],
            identity["clock_fixed_metric_F_velocity_hessian_is_4a"],
        )),
        "tensor_EH_kinetic_and_F_algebraic_shear_distinguished": all((
            identity["tensor_F_is_algebraic_shear_response"],
            identity["tensor_EH_principal_velocity_hessian_nonzero"],
        )),
        "omitted_C2_and_DH2_operators_change_quadratic_velocity_blocks": all((
            negative["omitted_C_squared_creates_quadratic_label_velocity"],
            negative["omitted_DH_squared_creates_quadratic_H_time_velocity"],
        )),
        "all_false_scope_outcomes_remain_false": all(
            EXPECTED_OUTCOMES[key] is False for key in (
                "full_metric_constraint_reduction_performed",
                "reduced_physical_spectrum_or_DOF_health_proved",
                "manuscript_exterior_or_observation_retested",
            )
        ),
    }
    valid = all((
        bool(dependency) and all(dependency.values()),
        identities_pass,
        negative_controls_pass,
        all(outcome_support_controls.values()),
        all(hash_controls.values()),
        all(semantic_controls.values()),
    ))

    # A mutation harness demonstrates that every single exact identity and
    # negative control is decision-essential.
    evidence = {**audit["identities"], **audit["negative_controls"]}
    single_false_controls = {}
    for key in evidence:
        mutated = deepcopy(evidence)
        mutated[key] = False
        single_false_controls[key] = not all(mutated.values())
    decision_controls = {
        "every_single_false_evidence_item_blocks_validity": all(single_false_controls.values()),
        "nonboolean_evidence_rejected": not all(
            isinstance(item, bool) and item for item in [*evidence.values(), "PASS"]
        ),
        "physical_closure_promotion_rejected": not _all_false({
            **EXPECTED_CLOSURE_FLAGS,
            "A3_full_reduced_DOF_health_proved": True,
        }),
    }
    valid = bool(valid and all(decision_controls.values()))

    status = (
        "PASS_DEPENDENCY_LOCKED_SILENT_MINKOWSKI_UNREDUCED_ACTION_AUDIT__"
        "C2_QUADRATIC_LABEL_VELOCITY_HESSIAN_ZERO__"
        "C3_CUBIC_HESSIAN_DERIVED__REDUCED_PHYSICAL_SPECTRUM_OPEN"
        if valid else
        "FAIL_INVALID_UNREDUCED_ACTION_AUDIT_NO_PROMOTION"
    )
    return {
        "artifact": CLAIM_ID,
        "model_version": MODEL_VERSION,
        "valid": valid,
        "status": status,
        "scientific_meaning": (
            "On the C2 track, the direct quadratic material-label velocity Hessian "
            "of the minimal silent F sector vanishes exactly. On the separate C3 "
            "track, the full cubic material-velocity Hessian is derived; the pure "
            "cubic Taylor jet adds none. For nonzero F_min the resulting polynomial "
            "is nontrivial but vanishes on y1+e1=0. These are unreduced perturbative "
            "action identities, not a reduced physical-spectrum result."
        ),
        "outcomes": EXPECTED_OUTCOMES,
        "physical_closure_flags": EXPECTED_CLOSURE_FLAGS,
        "identities": audit["identities"],
        "negative_controls": audit["negative_controls"],
        "outcome_support_controls": outcome_support_controls,
        "dependency_controls": dependency,
        "dependency_diagnostics": dependency_diagnostics,
        "hash_controls": hash_controls,
        "semantic_controls": semantic_controls,
        "decision_controls": decision_controls,
        "hashes": hashes,
        "results": _serialize(audit["compact_results"]),
        "open_work": (
            "full ADM/Dirac or gauge-invariant metric-clock-label-H reduction",
            "complete symmetry-compatible operator basis including C^2 and D_H^2",
            "kinetic eigenvalues, characteristics and strong-coupling scale",
            "source-derived branch selection and observational handoff",
        ),
    }


def main() -> int:
    try:
        report = evaluate()
        print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))
        return 0 if report["valid"] else 1
    except Exception as exc:  # fail closed with a compact machine-readable result
        print(json.dumps({
            "artifact": CLAIM_ID,
            "model_version": MODEL_VERSION,
            "valid": False,
            "status": "FAIL_EXCEPTION_NO_PROMOTION",
            "error": f"{type(exc).__name__}: {exc}",
        }, ensure_ascii=False, indent=2, sort_keys=True))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
