from __future__ import annotations

import ast
import inspect
import math
from dataclasses import dataclass

import sympy as sp

from p18bh_boundary_slot_count_theorem_gate import (
    boundary_rank_nullity_theorem,
    photon_readout_generators,
)
from p18bl_target_free_alpha_kernel_gate import (
    C3_ORDER,
    H_BRANCH,
    ORDER_NINE,
    QED_B1_PER_LEPTON,
    QED_B1_THREE_LEPTONS,
    current_action_embedding_audit,
    diagonal_sheet_normalization,
    exact_c3_mass_ratios,
    internal_inverse_alpha,
    solve_boundary_relation,
)


@dataclass(frozen=True)
class StructuralSignature:
    c3_order: int
    oriented_return_index: int
    order_nine: int
    locked_sheet_count: int
    photon_readout_rank: int
    hidden_kernel_dimension: int
    photon_helicity_count: int


@dataclass(frozen=True)
class SameStructureWitness:
    label: str
    maxwell_diagonal: float
    maxwell_mixing: float
    source_coefficient: float
    effective_unit_sheet_ratio: float
    inverse_alpha: float
    structure: StructuralSignature


def structural_signature() -> StructuralSignature:
    boundary = boundary_rank_nullity_theorem()
    return StructuralSignature(
        c3_order=C3_ORDER,
        oriented_return_index=H_BRANCH,
        order_nine=ORDER_NINE,
        locked_sheet_count=H_BRANCH,
        photon_readout_rank=boundary.readout_rank,
        hidden_kernel_dimension=boundary.kernel_dimension,
        photon_helicity_count=H_BRANCH,
    )


def exchange_symmetric_sheet_action_theorem() -> dict[str, object]:
    """Derive the physical charge invariant of two locked gauge sheets.

    Before locking, the exchange-symmetric quadratic sector is

        L=-1/4 F^T K F + J k^T A,
        K=a I_2+b 11^T,  k=kappa 1.

    The relative gauge field may be made massive without changing the
    surviving diagonal normalization.  Canonically normalizing that diagonal
    field gives q0^2=k^T K^{-1}k.  Exchange symmetry fixes the matrix form,
    but it does not fix a, b, or kappa.
    """

    a, b, kappa = sp.symbols("a b kappa", real=True)
    scale, field_scale = sp.symbols("r lambda", positive=True)
    identity = sp.eye(2)
    ones = sp.ones(2, 1)
    kinetic = a * identity + b * (ones * ones.T)
    source = kappa * ones

    q0_squared = sp.factor((source.T * kinetic.inv() * source)[0])
    effective_unit_sheet_ratio = sp.factor(q0_squared / 2)
    diagonal_kinetic = sp.factor((ones.T * kinetic * ones)[0])
    diagonal_source = sp.factor((ones.T * source)[0])
    canonical_diagonal_q0_squared = sp.factor(
        diagonal_source**2 / diagonal_kinetic
    )

    K_star, k_star = sp.symbols("K_star k_star", positive=True)
    eta = sp.factor(k_star**2 / K_star)
    field_redefinition_invariant = sp.simplify(
        (k_star / field_scale) ** 2
        / (K_star / field_scale**2)
        - eta
    )
    classical_equation_invariant = sp.simplify(
        (scale * k_star) / (scale * K_star) - k_star / K_star
    )
    quantum_action_scale_change = sp.simplify(
        (scale * k_star) ** 2 / (scale * K_star) - scale * eta
    )

    return {
        "action": "L=-F^T K F/4+J k^T A+L_lock",
        "kinetic_matrix": "K=a I_2+b 11^T",
        "source_vector": "k=kappa 1",
        "positive_action_conditions": "a>0 and a+2b>0",
        "kinetic_eigenvalues": (a, a + 2 * b),
        "diagonal_kinetic_coefficient": diagonal_kinetic,
        "diagonal_source_coefficient": diagonal_source,
        "q0_squared": q0_squared,
        "effective_unit_sheet_ratio": effective_unit_sheet_ratio,
        "canonical_diagonal_agrees": sp.simplify(
            canonical_diagonal_q0_squared - q0_squared
        )
        == 0,
        "field_redefinition_leaves_k2_over_K_invariant": (
            field_redefinition_invariant == 0
        ),
        "common_action_rescaling_leaves_classical_Kinv_k_invariant": (
            classical_equation_invariant == 0
        ),
        "common_action_rescaling_changes_quantum_charge_by_r": (
            quantum_action_scale_change == 0
        ),
        "exchange_symmetry_fixes_q0_squared": False,
        "reference_value_used": False,
    }


def hidden_boundary_coefficient_theorem() -> dict[str, object]:
    """Expose every coefficient installed in the alpha/N readout theorem."""

    alpha, c_budget, g_source, s_interface = sp.symbols(
        "alpha c g s", positive=True
    )
    trace_budget, k_scalar, u_source = sp.symbols(
        "T k_S u", positive=True
    )
    N = sp.Integer(boundary_rank_nullity_theorem().kernel_dimension)

    isotropic_density = sp.simplify(trace_budget / N)
    response = sp.simplify(
        g_source * s_interface**2 * isotropic_density
    )
    alpha_response = sp.simplify(
        response.subs(trace_budget, c_budget * alpha)
    )

    # If the trace is generated by an ordinary quadratic source rather than
    # constrained to alpha, minimization gives rho=(u/k_S) I_N.  The factor N
    # then disappears from the normalized two-helicity response.
    unconstrained_density = sp.simplify(u_source / k_scalar)
    unconstrained_response = sp.simplify(
        g_source * s_interface**2 * unconstrained_density
    )

    return {
        "general_O34_action": (
            "S=(k_T/2)Tr(rho_0^2)+(k_S/(2N))(Tr(rho)-T)^2"
            "+Tr[Lambda(C^T C-s^2 I_2)]/2-g Tr_2[J C^T rho C]"
        ),
        "zero_source_density": "rho_*=(T/N) I_N",
        "scalar_response": response,
        "installed_alpha_trace_budget": "T=c*alpha",
        "alpha_response": alpha_response,
        "unit_candidate": "c=g=s=1",
        "unconstrained_trace_action": (
            "S_trace=(k_S/(2N))(Tr rho)^2-u Tr rho"
        ),
        "unconstrained_density": unconstrained_density,
        "unconstrained_response": unconstrained_response,
        "N_cancels_without_installed_trace_budget": not (
            unconstrained_response.has(N)
        ),
        "N_and_O34_fix_c_g_s": False,
        "trace_budget_derived_from_current_action": False,
        "reference_value_used": False,
    }


def c3_interface_family_theorem() -> dict[str, object]:
    """Show that C3 covariance leaves a continuous hidden interface circle."""

    cyclic = sp.zeros(C3_ORDER)
    for row in range(C3_ORDER):
        cyclic[(row + 1) % C3_ORDER, row] = 1

    D_c = (cyclic + cyclic.T) / sp.sqrt(6)
    D_s = sp.I * (cyclic - cyclic.T) / sp.sqrt(6)
    basis = (D_c, D_s)
    gram = sp.Matrix(
        [
            [sp.simplify(sp.trace(left.H * right)) for right in basis]
            for left in basis
        ]
    )

    phi = sp.symbols("phi", real=True)
    D_phi = sp.cos(phi) * D_c + sp.sin(phi) * D_s
    norm_phi = sp.trigsimp(sp.trace(D_phi.H * D_phi))

    sigma_1 = sp.Matrix([[0, 1], [1, 0]])
    sigma_2 = sp.Matrix([[0, -sp.I], [sp.I, 0]])
    deltas = tuple(
        sp.kronecker_product(D, sigma) / sp.sqrt(2)
        for D in basis
        for sigma in (sigma_1, sigma_2)
    )
    gammas = photon_readout_generators()
    photon_overlaps = tuple(
        sp.simplify(sp.trace(gamma.H * delta))
        for gamma in gammas
        for delta in deltas
    )

    return {
        "C3_commutant_basis": (
            "D_c=(P+P^T)/sqrt(6)",
            "D_s=i(P-P^T)/sqrt(6)",
        ),
        "basis_is_Hermitian": all(D.H == D for D in basis),
        "basis_is_traceless": all(sp.trace(D) == 0 for D in basis),
        "basis_commutes_with_C3": all(
            sp.simplify(cyclic * D - D * cyclic) == sp.zeros(C3_ORDER)
            for D in basis
        ),
        "basis_gram_is_identity": gram == sp.eye(2),
        "continuous_family": "D(phi)=cos(phi)D_c+sin(phi)D_s",
        "continuous_family_unit_norm": sp.simplify(norm_phi - 1) == 0,
        "all_basis_interfaces_are_hidden": all(
            overlap == 0 for overlap in photon_overlaps
        ),
        "C3_selects_unique_interface_direction": False,
        "O34_isotropy_makes_phi_invisible_at_leading_order": True,
        "reference_value_used": False,
    }


def symbolic_alpha_underdetermination_theorem() -> dict[str, object]:
    """Prove the exact continuous fibre of the completed alpha relation."""

    A, beta_1, R0 = sp.symbols("A beta_1 R_0", positive=True)
    eta, xi = sp.symbols("eta xi", positive=True)
    beta_boundary, c_budget, g_source, s_interface = sp.symbols(
        "b c g s", positive=True
    )
    N = sp.symbols("N", positive=True)
    delta = sp.symbols("Delta", real=True)
    y = sp.symbols("y", positive=True)

    omega = sp.simplify(
        beta_boundary * c_budget * g_source * s_interface**2 / N
    )
    Y = A / eta + beta_1 * sp.log(xi**3 * R0) + delta
    polynomial = sp.expand(y**2 - Y * y + omega)
    large_root = sp.simplify((Y + sp.sqrt(Y**2 - 4 * omega)) / 2)
    large_root_residual = sp.simplify(
        large_root**2 - Y * large_root + omega
    )

    delta_fibre = sp.simplify(
        y + omega / y - A / eta - beta_1 * sp.log(xi**3 * R0)
    )
    fibre_residual = sp.simplify(polynomial.subs(delta, delta_fibre))
    fibre_discriminant = sp.simplify(
        (Y**2 - 4 * omega).subs(delta, delta_fibre)
    )
    fibre_discriminant_identity = sp.simplify(
        fibre_discriminant - (y - omega / y) ** 2
    )

    # Work in logarithmic positive parameters.  The map from seven
    # continuous coefficients to the two combinations (Y, omega) has generic
    # rank two and therefore an exact five-dimensional invariance fibre.
    U, W = sp.symbols("U W", positive=True)
    combination_jacobian = sp.Matrix(
        [
            [-U, 3 * beta_1, 1, 0, 0, 0, 0],
            [0, 0, 0, W, W, W, 2 * W],
        ]
    )
    combination_nullspace = combination_jacobian.nullspace()

    D = sp.symbols("D", positive=True)
    output_sensitivity = sp.Matrix(
        [
            [
                -U / D,
                3 * beta_1 / D,
                1 / D,
                -W / (y * D),
                -W / (y * D),
                -W / (y * D),
                -2 * W / (y * D),
            ]
        ]
    )

    t, u = sp.symbols("t u", positive=True)
    core_shifted_Y = (
        A / eta
        + beta_1 * sp.log((t * xi) ** 3 * R0)
        + delta
        - 3 * beta_1 * sp.log(t)
    )
    eta_prime = sp.symbols("eta_prime", positive=True)
    eta_compensated_Y = (
        A / eta_prime
        + beta_1 * sp.log(xi**3 * R0)
        + delta
        + A / eta
        - A / eta_prime
    )
    trace_source_shifted_omega = sp.simplify(
        beta_boundary
        * (u * c_budget)
        * (g_source / u)
        * s_interface**2
        / N
    )
    interface_source_shifted_omega = sp.simplify(
        beta_boundary
        * c_budget
        * (g_source / u**2)
        * (u * s_interface) ** 2
        / N
    )

    return {
        "coefficient_order": (
            "ln(eta)",
            "ln(xi)",
            "Delta",
            "ln(b)",
            "ln(c)",
            "ln(g)",
            "ln(s)",
        ),
        "Y": Y,
        "omega": omega,
        "equation": "y^2-Y*y+omega=0",
        "large_root": large_root,
        "large_root_residual_zero": large_root_residual == 0,
        "large_branch_condition": "y>sqrt(omega)",
        "arbitrary_positive_output_fibre": delta_fibre,
        "fibre_residual_zero": fibre_residual == 0,
        "fibre_discriminant_identity": fibre_discriminant_identity == 0,
        "combination_jacobian": combination_jacobian,
        "combination_jacobian_rank": combination_jacobian.rank(),
        "combination_fibre_dimension": len(combination_nullspace),
        "output_sensitivity_rank": output_sensitivity.rank(),
        "fixed_output_fibre_dimension": 7 - output_sensitivity.rank(),
        "dy_deta_sign_on_large_branch": "negative",
        "dy_dDelta_sign_on_large_branch": "positive",
        "core_scale_finite_matching_degeneracy": sp.simplify(
            core_shifted_Y - Y
        )
        == 0,
        "eta_finite_matching_degeneracy": sp.simplify(
            eta_compensated_Y - Y
        )
        == 0,
        "trace_source_degeneracy": sp.simplify(
            trace_source_shifted_omega - omega
        )
        == 0,
        "interface_source_degeneracy": sp.simplify(
            interface_source_shifted_omega - omega
        )
        == 0,
        "free_coefficient_can_translate_any_output": True,
        "translation_is_a_prediction": False,
        "reference_value_used": False,
    }


def _same_structure_witness(
    label: str,
    a: float,
    b: float,
    kappa: float,
) -> SameStructureWitness:
    if a <= 0.0 or a + 2.0 * b <= 0.0 or kappa <= 0.0:
        raise ValueError("the locked-sheet action must be positive")

    eta_effective = kappa**2 / (a + 2.0 * b)
    normalization = diagonal_sheet_normalization(
        h=H_BRANCH,
        order=ORDER_NINE,
        sheet_count=H_BRANCH,
        unit_sheet_ratio=eta_effective,
    )
    tau_over_e, muon_over_e = exact_c3_mass_ratios()
    Y = internal_inverse_alpha(tau_over_e, muon_over_e, normalization)
    N = boundary_rank_nullity_theorem().kernel_dimension
    inverse_alpha = solve_boundary_relation(
        Y,
        N,
        boundary_matching_coefficient=QED_B1_THREE_LEPTONS,
        interface_gain=1.0,
    )
    return SameStructureWitness(
        label=label,
        maxwell_diagonal=a,
        maxwell_mixing=b,
        source_coefficient=kappa,
        effective_unit_sheet_ratio=eta_effective,
        inverse_alpha=inverse_alpha,
        structure=structural_signature(),
    )


def same_structure_different_alpha_witnesses() -> tuple[
    SameStructureWitness, SameStructureWitness
]:
    """Two positive actions with identical discrete data and different alpha."""

    return (
        _same_structure_witness("unit Maxwell coefficient", 1.0, 0.0, 1.0),
        _same_structure_witness("doubled Maxwell coefficient", 2.0, 0.0, 1.0),
    )


def current_action_scope_ledger() -> dict[str, object]:
    embedding = current_action_embedding_audit()
    return {
        "current_p01_fields": embedding["p01_bulk_fields"],
        "additive_sheet_count_derived": embedding[
            "additive_Maxwell_sheet_count_derived"
        ],
        "HermV_boundary_field_present": embedding[
            "HermV_boundary_field_present_in_current_action"
        ],
        "hidden_density_present": embedding[
            "SymK_hidden_density_present_in_current_action"
        ],
        "O34_derived_from_current_symmetry": embedding[
            "O34_isotropy_follows_from_current_C3xU1_symmetry"
        ],
        "minimal_completion_is_stronger_than_current_action": True,
        "underdetermination_survives_minimal_completion": True,
        "reference_value_used": False,
    }


def source_firewall() -> dict[str, object]:
    module = inspect.getmodule(source_firewall)
    source = inspect.getsource(module)
    forbidden_literals = (
        "COD" + "ATA",
        "OBS" + "ERVED",
        "137.03" + "5999177",
    )
    violations = tuple(
        token for token in forbidden_literals if token in source
    )

    tree = ast.parse(source)
    local_imports = tuple(
        sorted(
            {
                node.module
                for node in ast.walk(tree)
                if isinstance(node, ast.ImportFrom)
                and node.module is not None
                and node.module.startswith("p")
            }
        )
    )
    allowed_local_imports = {
        "p18bh_boundary_slot_count_theorem_gate",
        "p18bl_target_free_alpha_kernel_gate",
    }
    disallowed_local_imports = tuple(
        name for name in local_imports if name not in allowed_local_imports
    )
    return {
        "forbidden_literal_violations": violations,
        "local_imports": local_imports,
        "disallowed_local_imports": disallowed_local_imports,
        "reference_module_imported": False,
        "runtime_reference_free": not violations
        and not disallowed_local_imports,
    }


def theorem_conclusion() -> tuple[str, ...]:
    return (
        "The discrete results h=2, rank(R_gamma)=2 and N=34 remain exact within their stated conditional representations.",
        "Even after granting the strongest minimal exchange-symmetric sheet action and O(34) boundary completion, continuous physical coefficients remain.",
        "Actions with the same discrete and symmetry data therefore produce different values of alpha.",
        "Choosing a finite matching term or normalization from a desired output translates that output into a free coefficient; it does not predict it.",
        "A unique alpha requires an additional microscopic quantization or dynamical theorem plus complete QED/EW/nonleptonic matching.",
    )


def run_gate() -> None:
    signature = structural_signature()
    sheet_action = exchange_symmetric_sheet_action_theorem()
    hidden_action = hidden_boundary_coefficient_theorem()
    interface_family = c3_interface_family_theorem()
    theorem = symbolic_alpha_underdetermination_theorem()
    witness_a, witness_b = same_structure_different_alpha_witnesses()
    scope = current_action_scope_ledger()
    firewall = source_firewall()

    assert signature.oriented_return_index == 2
    assert signature.photon_readout_rank == 2
    assert signature.hidden_kernel_dimension == 34
    assert sheet_action["canonical_diagonal_agrees"]
    assert sheet_action[
        "field_redefinition_leaves_k2_over_K_invariant"
    ]
    assert sheet_action[
        "common_action_rescaling_leaves_classical_Kinv_k_invariant"
    ]
    assert sheet_action[
        "common_action_rescaling_changes_quantum_charge_by_r"
    ]
    assert sheet_action["exchange_symmetry_fixes_q0_squared"] is False
    assert hidden_action["N_cancels_without_installed_trace_budget"]
    assert hidden_action["N_and_O34_fix_c_g_s"] is False
    assert hidden_action["trace_budget_derived_from_current_action"] is False
    assert interface_family["basis_is_Hermitian"]
    assert interface_family["basis_is_traceless"]
    assert interface_family["basis_commutes_with_C3"]
    assert interface_family["basis_gram_is_identity"]
    assert interface_family["continuous_family_unit_norm"]
    assert interface_family["all_basis_interfaces_are_hidden"]
    assert interface_family["C3_selects_unique_interface_direction"] is False
    assert theorem["fibre_residual_zero"]
    assert theorem["fibre_discriminant_identity"]
    assert theorem["large_root_residual_zero"]
    assert theorem["combination_jacobian_rank"] == 2
    assert theorem["combination_fibre_dimension"] == 5
    assert theorem["output_sensitivity_rank"] == 1
    assert theorem["fixed_output_fibre_dimension"] == 6
    assert theorem["core_scale_finite_matching_degeneracy"]
    assert theorem["eta_finite_matching_degeneracy"]
    assert theorem["trace_source_degeneracy"]
    assert theorem["interface_source_degeneracy"]
    assert theorem["translation_is_a_prediction"] is False
    assert witness_a.structure == witness_b.structure
    assert witness_a.effective_unit_sheet_ratio != (
        witness_b.effective_unit_sheet_ratio
    )
    assert not math.isclose(
        witness_a.inverse_alpha,
        witness_b.inverse_alpha,
        rel_tol=1.0e-12,
    )
    assert scope["additive_sheet_count_derived"] is False
    assert scope["HermV_boundary_field_present"] is False
    assert scope["hidden_density_present"] is False
    assert scope["O34_derived_from_current_symmetry"] is False
    assert scope["underdetermination_survives_minimal_completion"]
    assert firewall["runtime_reference_free"]

    print("p18bn alpha underdetermination theorem gate")
    print("structural signature")
    print(signature)
    print()
    print("exchange-symmetric locked-sheet action theorem")
    print(sheet_action)
    print()
    print("hidden boundary coefficient theorem")
    print(hidden_action)
    print()
    print("C3 interface family theorem")
    print(interface_family)
    print()
    print("exact identifiability theorem")
    print(theorem)
    print()
    print("same-structure, different-alpha witnesses")
    print(witness_a)
    print(witness_b)
    print()
    print("current-action scope")
    print(scope)
    print()
    print("source firewall")
    print(firewall)
    print()
    print("theorem conclusion")
    for item in theorem_conclusion():
        print(f"- {item}")
    print()
    print(
        "STATUS: OPEN_MICROSCOPIC_NORMALIZATION_AND_COMPLETE_MATCHING__"
        "PASS_TARGET_INDEPENDENT_ALPHA_UNDERDETERMINATION_THEOREM"
    )


if __name__ == "__main__":
    run_gate()
