# Notation header:
# signature (+---); compact branch uses positive metric functions
# B=exp(-r_s/r), A=exp(r_s/r) in ds^2=B c^2 dt^2-A dSigma^2.
#
# This gate repairs the foundational reading exposed by p05j-p05m:
# the structural medium modulus F_min was being counted as an ordinary RHS
# stress on a geometry that is already produced by the RefG medium mechanism.
# That is double counting.  The primary repair is a source ledger, not a
# compensating residual fit.

from __future__ import annotations

import sympy as sp

from p05k_full_compact_source_residual_gate import (
    derive_compact_projected_full_residual_gate,
    derive_full_raw_fmin_plus_ldelta_residual_gate,
)
from p05l_compact_fmin_weight_matching_gate import (
    derive_compact_fmin_weight_from_residual_matching_gate,
)
from p05m_fmin_tadpole_renormalization_gate import (
    derive_compact_linear_tail_vs_solar_family_gate,
    derive_unit_background_tadpole_subtraction_gate,
)


def derive_compact_no_double_count_source_ledger_gate():
    """
    Separate structural branch mechanics from active RHS matter.

    RefG reads the compact exponential exterior as geometry generated by the
    projected deficit medium source.  The raw F_min modulus is a structural
    constitutive part of the medium.  On the compact branch it is not also an
    additional active matter source on the same geometry.

    The previous residual tests are kept, but their meaning changes:

      - raw F_min + L_Delta leaves a tensor residual;
      - projected L_Delta alone closes the compact exterior;
      - residual-matching Omega_F=0 is circular and is not used;
      - tadpole subtraction cannot fix the raw tail;
      - the Solar F_min modulus cannot be forced into the compact exterior as
        an ordinary RHS stress.

    Therefore the correct repair is the ledger rule:

        compact active RHS = L_Delta_perp,
        compact structural sector = F_min,
        active_rhs(F_min | compact exterior) = 0 by role, not by residual fit.

    This gate closes the double-counting diagnosis.  p05r writes the same
    ledger as an explicit variational source-role projector.
    """
    raw = derive_full_raw_fmin_plus_ldelta_residual_gate()
    projected = derive_compact_projected_full_residual_gate()
    matching = derive_compact_fmin_weight_from_residual_matching_gate()
    tadpole = derive_unit_background_tadpole_subtraction_gate()
    solar_tail = derive_compact_linear_tail_vs_solar_family_gate()

    structural_symbol = sp.Symbol("F_min_structural")
    active_symbol = sp.Symbol("F_min_active")
    compact_active_fmin = sp.Integer(0)
    compact_structural_fmin = structural_symbol
    solar_active_fmin = active_symbol

    ledger_consistent = (
        raw["full_raw_residual_status"] == "FAIL_RAW_FMIN_ADDS_NONZERO_TENSOR_RESIDUAL"
        and projected["projected_compact_residual_status"]
        == "PASS_COMPACT_BRANCH_CLOSES_WHEN_ACTIVE_FMIN_WEIGHT_IS_ZERO"
        and matching["compact_fmin_weight_status"]
        == "FAIL_RESIDUAL_MATCHING_OMEGA_F_ZERO_IS_CIRCULAR_WITHOUT_ACTION_MECHANISM"
        and tadpole["tadpole_subtraction_status"]
        == "FAIL_TADPOLE_SUBTRACTION_DOES_NOT_REMOVE_COMPACT_LINEAR_TAIL"
        and solar_tail["compact_tail_vs_solar_family_status"]
        == "FAIL_SOLAR_PHYSICAL_SLICE_CONFLICTS_WITH_COMPACT_FMIN_TAIL_SILENCING"
        and compact_active_fmin == 0
        and compact_structural_fmin == structural_symbol
        and solar_active_fmin == active_symbol
    )

    return {
        "no_double_count_ledger_status": (
            "PASS_COMPACT_FMIN_RAW_RESIDUAL_IS_LEDGER_DOUBLE_COUNT_NOT_PHYSICAL_RHS"
            if ledger_consistent
            else "CHECK_COMPACT_FMIN_SOURCE_LEDGER"
        ),
        "raw_full_residual_diagnostic": raw["full_raw_residual_status"],
        "projected_compact_residual": projected["projected_compact_residual_status"],
        "rejected_residual_matching": matching["compact_fmin_weight_status"],
        "tadpole_repair_diagnostic": tadpole["tadpole_subtraction_status"],
        "solar_tail_diagnostic": solar_tail["compact_tail_vs_solar_family_status"],
        "compact_active_rhs_ledger": {
            "L_Delta_perp": "active compact RHS source",
            "F_min": compact_active_fmin,
        },
        "compact_structural_ledger": {
            "F_min": compact_structural_fmin,
            "role": "medium constitutive structure and branch mechanics",
        },
        "solar_diffuse_ledger": {
            "F_min": solar_active_fmin,
            "role": "diffuse weak-field medium response",
        },
        "main_reading": (
            "The raw compact F_min tensor residual is the mark of double "
            "counting: the same medium structure was first used as the "
            "geometric mechanism and then added again as matter on the RHS."
        ),
        "article_direction": (
            "Write the compact branch with a source ledger: the projected "
            "deficit operator is the active exterior source; F_min is the "
            "structural medium sector and is not added again as an ordinary "
            "compact RHS stress."
        ),
        "remaining_formal_work": (
            "p05r writes this ledger as an explicit variational projector.  "
            "The remaining work is compact-core dynamics, rotation, and "
            "observational tests, not the source-ledger separation itself."
        ),
    }


if __name__ == "__main__":
    print("=" * 72)
    print("PHASE 18p: No-double-count source ledger")
    print("=" * 72)
    result = derive_compact_no_double_count_source_ledger_gate()
    for key, value in result.items():
        print(f"{key:44s}: {value}")
