# Notation header (see NOTATION.md):
# signature (+---); Y = g^mn d_m Phi d_n Phi; B^AB = -g^mn d_m phi^A d_n phi^B.
# T_mn = 2*dL/dg^mn - g_mn*L; off-diagonal symmetric variables use factor 1.
# Horndeski/EFT bridge only: X = -1/2 g^mn d_m Phi d_n Phi, so Y = -2X.
# Active coefficient scheme: this file uses particle-sector normal forms;
# no active c_Y sign claim is made here.

"""PHASE 38c (p11e): the C3-invariant effective potential and the division
of labor between sqrt(2) and 2/9.

Continues p11d.  The sqrt-mass triple is represented as the spectrum of a
real circulant 3x3 matrix

    M = mu*I + z*P + conj(z)*P^2,      z = (mu*A/2)*exp(i*theta),

(P = cyclic shift), whose eigenvalues are exactly the C3 form
mu*(1 + A*cos(theta + 2*pi*k/3)).  The full ring of spectral invariants is
generated by tr M, tr M^2, tr M^3, equivalently by

    S = 3*mu^2        (singlet channel intensity; depends on mu only),
    D = 6*|z|^2       (doublet channel intensity; depends on |z| only),
    K = 2*Re(z^3) = 2*|z|^3*cos(3*theta)   (the only theta-carrier).

Results proved here:

  T1 (exact). CIRCULANT DICTIONARY: eigenvalues, tr M, tr M^2, tr M^3
      reproduce the C3 form and the (S, D, K) coordinates; theta enters
      the invariant ring ONLY through cos(3*theta).

  T2 (exact + data). THETA-BLINDNESS THEOREM: for ANY spectral-invariant
      potential V(tr M, tr M^2, tr M^3), stationarity in theta requires
      sin(3*theta) = 0 or dV/d(trM^3) = 0 at the point.  The measured
      theta_obs = 0.2222248 +- 6.3e-6 (p11b) sits ~3.5e4 sigma away from
      the nearest sin(3*theta)=0 lock point (theta=0).  Hence the cubic
      invariant is QUIET on the physical point, the invariant potential
      is theta-blind there, and theta MUST be fixed by structure beyond
      the spectral invariants -- exactly the order-9 framed lattice of
      p11/p11d (odometer + spinorial h=2).  The 9-fold framing is
      therefore NECESSARY, not optional.

  T3 (exact). EQUIPARTITION FROM CHANNEL-EXCHANGE SYMMETRY: with the
      cubic quiet, the minimal invariant potential through quartic order
      is V = alpha*S + beta*D + a*S^2 + b*D^2 + c*S*D.  Since S = 3*mu^2
      and D = 6*|z|^2 are independent coordinates, stationarity gives
      V_S = 0 and V_D = 0.  If V is symmetric under the channel exchange
      S <-> D  (alpha = beta, a = b), the symmetric branch S = D is a
      stationary point, and it is a minimum iff a > 0 and 2a > c.  On
      that branch A = sqrt(2) EXACTLY (S = D <=> |z| = mu/sqrt(2)).
      Conversely, per-MODE democracy (|z| = mu) gives A = 2, Q = 1 --
      the degenerate edge excluded by data (p11d).

Net state of the task after p11d + p11e:
    sqrt(2)  <==  channel-exchange symmetry of the quartic C3 potential
                  (ONE symmetry statement),
    2/9      <==  unit braid anholonomy + spinorial framing
                  (ONE topology statement + one candidate map),
and the theta-blindness theorem PROVES these two mechanisms cannot mix:
the potential cannot do theta's job.  The covariant action EXISTS
(EH + F_min); what is open is its LEPTON SOLUTION SECTOR -- the
localized C3 oscillon states, the (S, D) effective potential they
inherit from F_min, and the framed transport around the defect.  Note
the determinant channel I3 = det(B) generates the cubic invariant at
action level (E^3 + conj(E)^3 = 27 det Q, p11; an algebraic statement,
not a gravity-source claim), and the data demand it quiet here -- the THIRD det-silencing in the theory (raw-invariant
obstruction p05j/p05k; determinant-lock rejection in the Solar
appendix), suggesting one shared mechanism.

Run:  python p11e_c3_invariant_potential_gate.py all
"""

import math
import sys

import sympy as sp


THETA_OBS = 0.222224761
THETA_SIGMA = 6.25e-06


# --- T1: circulant dictionary ---------------------------------------------------

def sym_circulant_dictionary():
    mu, A, th = sp.symbols("mu A theta", positive=True)
    z = (mu * A / 2) * sp.exp(sp.I * th)
    w = sp.exp(2 * sp.pi * sp.I / 3)

    # eigenvalues of mu*I + z*P + conj(z)*P^2: mu + z*w^k + conj(z*w^k)
    eigs = [sp.re(mu + z * w**k + sp.conjugate(z) * w**(-k)) for k in range(3)]
    target = [mu * (1 + A * sp.cos(th + 2 * sp.pi * k / 3)) for k in range(3)]
    # eigenvalue sets agree as multisets; compare symmetric sums instead of order
    r_e1 = sp.simplify(sum(eigs) - sum(target))
    r_e2 = sp.simplify(sum(x**2 for x in eigs) - sum(x**2 for x in target))
    r_e3 = sp.simplify(sp.expand_trig(sp.simplify(
        sp.prod(eigs) - sp.prod(target))))

    # invariant coordinates
    S = 3 * mu**2
    D = 6 * (sp.Abs(z)) ** 2
    K = 2 * sp.re(z**3)
    r_S = sp.simplify(sum(eigs) ** 2 / 3 - S)
    r_D = sp.simplify(sum(x**2 for x in eigs) - S - D)
    # tr M^3 carries theta only through cos(3 theta)
    trM3 = sp.simplify(sum(x**3 for x in eigs))
    r_K = sp.simplify(sp.expand_trig(trM3
                                     - (3 * mu**3 + sp.Rational(9, 2) * mu**3 * A**2 / 2 * 2
                                        + 3 * K)))
    # NB: r_K checks trM3 = 3 mu^3 + (9/2) mu^3 A^2/... explicit closed form below
    return {
        "eigen_sum_residual": r_e1,
        "eigen_sq_residual": r_e2,
        "eigen_prod_residual": r_e3,
        "S_residual": r_S,
        "D_residual": r_D,
        "trM3_minus_closed_form": r_K,
    }


# --- T2: theta-blindness theorem -------------------------------------------------

def sym_theta_blindness():
    """dV/dtheta for general invariant V(e1, e2, e3): proportional to
    sin(3 theta) times dV/d(trM^3)."""
    mu, A, th = sp.symbols("mu A theta", positive=True)
    e1 = 3 * mu
    e2 = 3 * mu**2 + sp.Rational(3, 2) * mu**2 * A**2
    zmod = mu * A / 2
    e3 = 3 * mu**3 + 9 * mu * zmod**2 + 2 * zmod**3 * sp.cos(3 * th) * 2
    # only e3 carries theta:
    de3 = sp.simplify(sp.diff(e3, th))
    expected = -12 * zmod**3 * sp.sin(3 * th)
    return {
        "de1_dtheta": sp.diff(e1, th),
        "de2_dtheta": sp.diff(e2, th),
        "de3_dtheta_minus_expected": sp.simplify(de3 - expected),
    }


def theta_lock_exclusion():
    """Distance of theta_obs from the nearest sin(3 theta)=0 lock point."""
    lock_points = [0.0, math.pi / 3]
    nearest = min(lock_points, key=lambda x: abs(THETA_OBS - x))
    pull = abs(THETA_OBS - nearest) / THETA_SIGMA
    return {
        "nearest_invariant_lock": nearest,
        "pull_sigma": pull,
        "active_cubic_excluded": pull > 100.0,
        "conclusion": (
            "the spectral-invariant potential is theta-blind at the physical "
            "point; theta is fixed by the order-9 framed structure (p11d), "
            "which is therefore necessary, not optional"
        ),
    }


# --- T3: equipartition from channel-exchange symmetry ----------------------------

def sym_channel_exchange_theorem():
    """V = alpha*S + beta*D + a*S^2 + b*D^2 + c*S*D on independent (S, D).

    (i) symmetric case alpha=beta, a=b: S=D solves both stationarity
        equations with S = -alpha/(2a + c) (interior solution exists for
        alpha<0, 2a+c>0);
    (ii) on S=D the Hessian [[2a, c], [c, 2b]] with a=b is positive
        definite iff a>0 and 2a>|c| (minimum condition);
    (iii) S=D <=> A=sqrt(2).
    """
    S, D, alpha, beta, a, b, c = sp.symbols("S D alpha beta a b c", real=True)
    V = alpha * S + beta * D + a * S**2 + b * D**2 + c * S * D
    VS = sp.diff(V, S)
    VD = sp.diff(V, D)

    # (i) symmetric case
    sym_subs = {beta: alpha, b: a}
    sol = sp.solve([VS.subs(sym_subs), VD.subs(sym_subs)], [S, D], dict=True)
    sym_branch = [s for s in sol if sp.simplify(s[S] - s[D]) == 0]
    branch_value = sp.simplify(sym_branch[0][S]) if sym_branch else None

    # (ii) Hessian eigenvalues at a=b: 2a+c and 2a-c
    hess = sp.Matrix([[sp.diff(V, S, 2), sp.diff(V, S, 1, D, 1)],
                      [sp.diff(V, D, 1, S, 1), sp.diff(V, D, 2)]]).subs(sym_subs)
    eigvals = list(hess.eigenvals().keys())

    # (iii) S = D <=> A = sqrt(2)
    mu, A = sp.symbols("mu A", positive=True)
    r_amp = sp.solve(sp.Eq(3 * mu**2, 6 * (mu * A / 2) ** 2), A)

    return {
        "symmetric_branch_exists": bool(sym_branch),
        "branch_S_equals_D_value": branch_value,
        "hessian_eigenvalues": eigvals,
        "minimum_condition": "a > 0 and 2a > |c| (both eigenvalues 2a+c, 2a-c positive)",
        "amplitude_on_branch": r_amp,
    }


# --- ledger -----------------------------------------------------------------------

def status_assessment(t1, t2, t2x, t3):
    t1_ok = all(v == 0 for v in t1.values())
    t2_ok = (t2["de1_dtheta"] == 0 and t2["de2_dtheta"] == 0
             and t2["de3_dtheta_minus_expected"] == 0)
    t3_ok = (t3["symmetric_branch_exists"]
             and t3["amplitude_on_branch"] == [sp.sqrt(2)])
    return {
        "T1": "PASS_CIRCULANT_DICTIONARY" if t1_ok else "T1_DID_NOT_VERIFY",
        "T2": "PASS_THETA_BLINDNESS_THEOREM" if t2_ok else "T2_DID_NOT_VERIFY",
        "T2_data": "PASS_ACTIVE_CUBIC_EXCLUDED_BY_THETA_DATA"
                   if t2x["active_cubic_excluded"] else "T2X_DID_NOT_VERIFY",
        "T3": "PASS_EQUIPARTITION_FROM_CHANNEL_EXCHANGE_SYMMETRY"
              if t3_ok else "T3_DID_NOT_VERIFY",
        "open": "OPEN_LEPTON_SOLUTION_SECTOR -- the action (EH + F_min) "
                "exists; open are three computable questions on it: "
                "(i) does the F_min-induced triplet potential carry the "
                "channel-exchange symmetry inside the p01 window; "
                "(ii) is the I3/det cubic channel quiet on the lepton "
                "branch (det already silenced in p05j/p05k and in the "
                "determinant-lock rejection -- candidate shared mechanism); "
                "(iii) framed-transport anholonomy of the localized "
                "C3 solution.",
    }


def do_not_claim():
    return [
        "Do not claim sqrt(2) is derived from the RG action: the "
        "channel-exchange symmetry is a sharp SUFFICIENT condition on an "
        "effective potential whose action-level origin is open.",
        "Do not claim 2/9 is derived: theta-blindness proves the invariant "
        "potential CANNOT fix theta (division of labor), but the framing "
        "lock's physical inputs (unit anholonomy, spinorial h=2) remain "
        "candidate-level (p11d).",
        "Do not claim the lepton solution sector is solved: the covariant "
        "action exists (EH + F_min), but its localized C3 oscillon states, "
        "their induced (S, D) potential, and the framed transport remain "
        "to be computed -- solitonic spectroscopy, not model-building.",
        "Do not read the quartic potential as unique: it is the MINIMAL "
        "invariant normal form through quartic order with the cubic quiet.",
    ]


# --- main ---------------------------------------------------------------------------

def main():
    print("=" * 72)
    print("PHASE 38c (p11e): C3-invariant potential -- division of labor")
    print("=" * 72)

    print("\n1. T1: circulant dictionary (symbolic residuals)")
    t1 = sym_circulant_dictionary()
    for key, val in t1.items():
        print(f"  {key} = {val}")

    print("\n2. T2: theta-blindness of the invariant ring")
    t2 = sym_theta_blindness()
    for key, val in t2.items():
        print(f"  {key} = {val}")

    t2x = theta_lock_exclusion()
    print(f"  nearest invariant lock point: theta = {t2x['nearest_invariant_lock']}")
    print(f"  pull of theta_obs from it    : {t2x['pull_sigma']:.0f} sigma"
          f"  -> active cubic excluded: {t2x['active_cubic_excluded']}")
    print(f"  conclusion: {t2x['conclusion']}")

    print("\n3. T3: equipartition from channel-exchange symmetry")
    t3 = sym_channel_exchange_theorem()
    print(f"  symmetric branch S=D exists  : {t3['symmetric_branch_exists']}"
          f"  (S = D = {t3['branch_S_equals_D_value']})")
    print(f"  Hessian eigenvalues (a=b)    : {t3['hessian_eigenvalues']}")
    print(f"  minimum condition            : {t3['minimum_condition']}")
    print(f"  amplitude on the branch      : A = {t3['amplitude_on_branch']}")

    print("\n4. STATUS")
    for key, val in status_assessment(t1, t2, t2x, t3).items():
        print(f"  {key}: {val}")

    print("\n5. do_not_claim")
    for item in do_not_claim():
        print(f"  - {item}")


if __name__ == "__main__":
    _ = sys.argv[1:]
    main()
