# Notation header:
# signature (+---); compact branch uses positive metric functions
# B=exp(-r_s/r), A=exp(r_s/r) in ds^2=B c^2 dt^2-A dSigma^2.
#
# Historical ledger after the p05j-p05m raw residual audit.
#
# Referee correction: the old "double-count" label is not an action-level
# closure by itself.  The raw absolute-invariant F_min stress is a real tensor
# if that raw action is used.  The repaired compact route is p05s: write F_min
# with phase-normalized compact-branch invariants so its compact stress
# vanishes before variation.  This file is kept as a rejected/provenance
# ledger for the older source-role wording.

from __future__ import annotations

import sympy as sp

from p05k_full_compact_source_residual_gate import (
    derive_compact_projected_full_residual_gate,
    derive_full_raw_fmin_plus_ldelta_residual_gate,
)
from p05l_compact_fmin_weight_matching_gate import (
    derive_compact_fmin_weight_from_residual_matching_gate,
)
from p05m_fmin_tadpole_renormalization_gate import (
    derive_compact_linear_tail_vs_solar_family_gate,
    derive_unit_background_tadpole_subtraction_gate,
)


def derive_compact_no_double_count_source_ledger_gate():
    """
    Separate structural branch mechanics from active RHS matter.

    RefG reads the compact exponential exterior as geometry generated by the
    projected deficit medium source.  The raw F_min modulus is a structural
    constitutive part of the medium.  On the compact branch it is not also an
    additional active matter source on the same geometry.

    The previous residual tests are kept, but their meaning changes:

      - raw F_min + L_Delta leaves a tensor residual;
      - projected L_Delta alone closes the compact exterior;
      - residual-matching Omega_F=0 is circular and is not used;
      - tadpole subtraction cannot fix the raw tail;
      - the Solar F_min modulus cannot be forced into the compact exterior as
        an ordinary RHS stress.

    Therefore the correct repair is the ledger rule:

        compact active RHS = L_Delta_perp,
        compact structural sector = F_min,
        active_rhs(F_min | compact exterior) = 0 by role, not by residual fit.

    Referee correction: this ledger does not close the variational objection
    by itself.  It records why the raw absolute-invariant insertion fails and
    hands the repair to p05s, where F_min is made quiet at the action level by
    phase-normalized compact invariants.
    """
    raw = derive_full_raw_fmin_plus_ldelta_residual_gate()
    projected = derive_compact_projected_full_residual_gate()
    matching = derive_compact_fmin_weight_from_residual_matching_gate()
    tadpole = derive_unit_background_tadpole_subtraction_gate()
    solar_tail = derive_compact_linear_tail_vs_solar_family_gate()

    structural_symbol = sp.Symbol("F_min_structural")
    active_symbol = sp.Symbol("F_min_active")
    compact_active_fmin = sp.Integer(0)
    compact_structural_fmin = structural_symbol
    solar_active_fmin = active_symbol

    ledger_consistent = (
        raw["full_raw_residual_status"] == "FAIL_RAW_FMIN_ADDS_NONZERO_TENSOR_RESIDUAL"
        and projected["projected_compact_residual_status"]
        == "SUPERSEDED_PROJECTED_RESIDUAL_ZERO__USE_P05S_ACTION_LEVEL_FMIN"
        and matching["compact_fmin_weight_status"]
        == "FAIL_RESIDUAL_MATCHING_OMEGA_F_ZERO_IS_CIRCULAR_WITHOUT_ACTION_MECHANISM"
        and tadpole["tadpole_subtraction_status"]
        == "FAIL_TADPOLE_SUBTRACTION_DOES_NOT_REMOVE_COMPACT_LINEAR_TAIL"
        and solar_tail["compact_tail_vs_solar_family_status"]
        == "FAIL_SOLAR_PHYSICAL_SLICE_CONFLICTS_WITH_COMPACT_FMIN_TAIL_SILENCING"
        and compact_active_fmin == 0
        and compact_structural_fmin == structural_symbol
        and solar_active_fmin == active_symbol
    )

    return {
        "no_double_count_ledger_status": (
            "SUPERSEDED_BY_P05S_PHASE_NORMALIZED_ACTION__DOUBLE_COUNT_LABEL_REJECTED"
            if ledger_consistent
            else "CHECK_COMPACT_FMIN_SOURCE_LEDGER"
        ),
        "raw_full_residual_diagnostic": raw["full_raw_residual_status"],
        "projected_compact_residual": projected["projected_compact_residual_status"],
        "rejected_residual_matching": matching["compact_fmin_weight_status"],
        "tadpole_repair_diagnostic": tadpole["tadpole_subtraction_status"],
        "solar_tail_diagnostic": solar_tail["compact_tail_vs_solar_family_status"],
        "compact_active_rhs_ledger": {
            "L_Delta_perp": "active compact RHS source",
            "F_min": compact_active_fmin,
        },
        "compact_structural_ledger": {
            "F_min": compact_structural_fmin,
            "role": "medium constitutive structure and branch mechanics",
        },
        "solar_diffuse_ledger": {
            "F_min": solar_active_fmin,
            "role": "diffuse weak-field medium response",
        },
        "main_reading": (
            "The raw compact F_min tensor residual is real for the raw "
            "absolute-invariant action.  Calling it double-counting was not "
            "enough; the action-level repair is the p05s phase-normalized "
            "compact F_min branch."
        ),
        "article_direction": (
            "Do not export the post-variation source ledger as the final "
            "answer.  Export p05s instead: compact F_min is written with "
            "phase-normalized strain invariants and is quiet on the pure-phase "
            "branch at the action level."
        ),
        "remaining_formal_work": (
            "Use p05s for the compact action-level source closure.  The "
            "continuous weak-to-compact loading law still has to be derived."
        ),
    }


if __name__ == "__main__":
    print("=" * 72)
    print("PHASE 18p: No-double-count source ledger")
    print("=" * 72)
    result = derive_compact_no_double_count_source_ledger_gate()
    for key, value in result.items():
        print(f"{key:44s}: {value}")
